"""In-memory analysis orchestration (`API-01`, enabling slice).

Framework-independent: no FastAPI/SQLAlchemy import. See `service.py` for
the full engine and `docs/architecture.md` §3 for this module's layer
placement ("Application services").
"""

from __future__ import annotations

from .service import (
    Analysis,
    AnalysisFailure,
    AnalysisNotFoundError,
    AnalysisNotReadyError,
    AnalysisNotRetryableError,
    AnalysisState,
    AnalysisStore,
    AnalysisStoreProtocol,
    ContextFieldNotEditableError,
    ContextVersionConflictError,
    FindingNotFoundError,
    GeneratedRuleOffer,
    InvalidRuleParametersError,
    QuestionNotFoundError,
    RowNotInFindingError,
    RuleNotFoundError,
    UnknownRuleColumnError,
    answer_guided_question,
    apply_ai_context_augmentation,
    cancel_analysis,
    confirm_context_fields,
    create_analysis,
    create_analysis_from_upload,
    create_rule,
    delete_rule,
    execute_rule_now,
    finalize_context,
    generate_rule_proposal,
    get_finding,
    get_finding_evidence,
    get_finding_row_context,
    get_findings,
    get_guided_questions,
    get_or_infer_context,
    get_profile,
    get_status,
    retry_analysis,
    run_analysis,
)

__all__ = [
    "Analysis",
    "AnalysisFailure",
    "AnalysisNotFoundError",
    "AnalysisNotReadyError",
    "AnalysisNotRetryableError",
    "AnalysisState",
    "AnalysisStore",
    "AnalysisStoreProtocol",
    "ContextFieldNotEditableError",
    "ContextVersionConflictError",
    "FindingNotFoundError",
    "GeneratedRuleOffer",
    "InvalidRuleParametersError",
    "QuestionNotFoundError",
    "RowNotInFindingError",
    "RuleNotFoundError",
    "UnknownRuleColumnError",
    "answer_guided_question",
    "apply_ai_context_augmentation",
    "cancel_analysis",
    "confirm_context_fields",
    "create_analysis",
    "create_analysis_from_upload",
    "create_rule",
    "delete_rule",
    "execute_rule_now",
    "finalize_context",
    "generate_rule_proposal",
    "get_finding",
    "get_finding_evidence",
    "get_finding_row_context",
    "get_findings",
    "get_guided_questions",
    "get_or_infer_context",
    "get_profile",
    "get_status",
    "retry_analysis",
    "run_analysis",
]
