"""In-memory analysis orchestration (`API-01`, enabling slice, `WP-023`).

A pure-Python, framework-independent orchestration engine wiring together
every already-delivered package (`ING-02` CSV parsing, `PROF-03`
profiling, `DET-01`/`DET-02`/`DET-SEC-01` detectors via `run_detectors()`,
`RISK-01` scoring) into one deterministic create-then-run pipeline over
the bundled demo dataset (`DEMO-01`). No FastAPI route, no persistence, no
AI provider, and no context inference exist yet — this module is the
"Application services"-layer engine a later, separate package will expose
over HTTP (`docs/architecture.md` §3).

`AnalysisState` is a documented 8-value subset of `docs/domain-model.md`
§5's 11-value `States` list (`inferring_context`/`awaiting_confirmation`/
`finalizing`/`deleted` excluded — those require packages that do not
exist yet). "State" and "current stage" are merged into this one field,
a disclosed, reversible simplification.

`cancel_analysis` is only effective while an analysis is `QUEUED`: true
mid-pipeline cancellation requires real bounded background execution
(`JOB-01`, not yet built) — `run_analysis` executes synchronously to
completion within one call, so no "active and cancellable" window exists
yet.

Every `Analysis.security_exposure` is fixed to the disabled/
no-transmission `SecurityExposureState` — no `AI-01`/`AI-02` provider
exists yet, matching `docs/product-requirements.md` §5.7's "graceful
AI-disabled operation" requirement structurally.

Framework-independent: no FastAPI/SQLAlchemy/pydantic import (this module
deliberately also avoids `version_info`/`config`, which would transitively
pull in pydantic `Settings` — a disclosed, conservative choice). Stdlib
only (`dataclasses`, `enum`, `datetime`, `uuid`, `hashlib`). No
`eval`/`exec` anywhere in this module.
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from enum import StrEnum

from ..demo_data import SEED, generate
from ..detectors.catalogue import DETECTORS
from ..detectors.contract import FindingCandidate, SecurityExposureState
from ..detectors.engine import run_detectors
from ..domain.parsing import Dataset, DatasetFormat, DatasetSourceType
from ..parsers.csv_parser import parse_csv
from ..profiling.metrics import compute_dataset_profile
from ..profiling.schemas import DatasetProfile
from ..risk.scoring import (
    TrustAssessment,
    calculate_finding_priority_scores,
    calculate_trust_assessment,
)

_NO_EXPOSURE = SecurityExposureState(
    model_provider_enabled=False, sample_transmission_enabled=False
)
"""Every `Analysis` produced by `create_analysis` uses this fixed,
disabled exposure state — no AI/LLM provider exists yet (`AI-01`/
`AI-02`)."""

_DEMO_ORIGINAL_FILENAME = "sales_demo.csv"
_DEMO_STORAGE_LOCATION = "demo-data/sales_demo.csv"
"""References the real, committed demo dataset path/filename for
accuracy even though this module never reads it from disk — the
generated bytes are byte-identical to that file (`DEMO-01`'s own
drift-check precedent). A disclosed, forward-compatible choice for
whenever a real storage layer (`DB-01`) exists."""

_FAILURE_CODE = "analysis.pipeline_failed"
_FAILURE_MESSAGE = "Analysis pipeline raised an exception during execution"
"""Fixed, safe, non-leaking failure code/message — never includes raw
exception text, matching `DET-01` `engine.py`'s own safe-failure
precedent one layer more conservatively (no exception type name either)."""


class AnalysisState(StrEnum):
    """An 8-value documented subset of `docs/domain-model.md` §5's
    11-value `States` list. `inferring_context`, `awaiting_confirmation`,
    `finalizing`, and `deleted` are excluded — they require packages that
    do not exist yet (`CTX-01`'s context inference; a deletion package,
    `DEL-01`). This package's pipeline goes directly from `DETECTING` to
    `COMPLETED`.
    """

    QUEUED = "queued"
    VALIDATING = "validating"
    PARSING = "parsing"
    PROFILING = "profiling"
    DETECTING = "detecting"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass(frozen=True, slots=True)
class AnalysisFailure:
    """A safe, non-leaking failure description (`docs/domain-model.md`
    §5's "safe failure code and message" field), matching `DET-01`'s
    existing `SafeFailure` shape/precedent.
    """

    code: str
    message: str

    def __post_init__(self) -> None:
        if not self.code:
            raise ValueError("AnalysisFailure.code must not be empty")
        if not self.message:
            raise ValueError("AnalysisFailure.message must not be empty")


@dataclass(frozen=True, slots=True)
class Analysis:
    """One in-memory analysis record.

    Invariants tie every result field and terminal timestamp to `state`:
    `dataset_profile`/`findings`/`priority_scores`/`trust_assessment` are
    all empty/`None` unless `state == COMPLETED`; `completed_at` is set
    if and only if `state == COMPLETED`; `failure`/`failed_at` are set if
    and only if `state == FAILED`; `cancelled_at` is set if and only if
    `state == CANCELLED`; `priority_scores` is always 1:1 with `findings`.
    """

    analysis_id: str
    dataset: Dataset
    state: AnalysisState
    security_exposure: SecurityExposureState
    dataset_profile: DatasetProfile | None
    findings: tuple[FindingCandidate, ...]
    priority_scores: tuple[float, ...]
    trust_assessment: TrustAssessment | None
    failure: AnalysisFailure | None
    created_at: datetime
    started_at: datetime | None
    completed_at: datetime | None
    failed_at: datetime | None
    cancelled_at: datetime | None

    def __post_init__(self) -> None:
        if not self.analysis_id:
            raise ValueError("Analysis.analysis_id must not be empty")
        if len(self.priority_scores) != len(self.findings):
            raise ValueError("Analysis.priority_scores must be 1:1 with findings")

        is_completed = self.state is AnalysisState.COMPLETED
        if is_completed:
            if self.dataset_profile is None:
                raise ValueError("Analysis: dataset_profile is required when state is COMPLETED")
            if self.trust_assessment is None:
                raise ValueError("Analysis: trust_assessment is required when state is COMPLETED")
        else:
            if self.dataset_profile is not None:
                raise ValueError("Analysis: dataset_profile must be None unless state is COMPLETED")
            if self.findings:
                raise ValueError("Analysis: findings must be empty unless state is COMPLETED")
            if self.trust_assessment is not None:
                raise ValueError(
                    "Analysis: trust_assessment must be None unless state is COMPLETED"
                )
        if (self.completed_at is not None) != is_completed:
            raise ValueError("Analysis.completed_at must be set if and only if state is COMPLETED")

        is_failed = self.state is AnalysisState.FAILED
        if (self.failure is not None) != is_failed:
            raise ValueError("Analysis.failure must be set if and only if state is FAILED")
        if (self.failed_at is not None) != is_failed:
            raise ValueError("Analysis.failed_at must be set if and only if state is FAILED")

        is_cancelled = self.state is AnalysisState.CANCELLED
        if (self.cancelled_at is not None) != is_cancelled:
            raise ValueError("Analysis.cancelled_at must be set if and only if state is CANCELLED")


class AnalysisNotFoundError(Exception):
    """Raised by every getter/mutator below for an unknown `analysis_id`."""

    def __init__(self, analysis_id: str) -> None:
        super().__init__(f"Analysis not found: {analysis_id}")
        self.analysis_id = analysis_id


class AnalysisStore:
    """A minimal in-memory dict-backed store. No persistence
    (`DB-01`, not yet built) and no concurrency safety — disclosed,
    matching this package's stated non-goals.
    """

    def __init__(self) -> None:
        self._analyses: dict[str, Analysis] = {}

    def add(self, analysis: Analysis) -> None:
        self._analyses[analysis.analysis_id] = analysis

    def get(self, analysis_id: str) -> Analysis | None:
        return self._analyses.get(analysis_id)

    def replace(self, analysis: Analysis) -> None:
        self._analyses[analysis.analysis_id] = analysis


def _generate_demo_content() -> bytes:
    """Generate the bundled demo dataset's CSV bytes in-memory —
    deterministic, byte-identical to the committed
    `demo-data/sales_demo.csv` (`DEMO-01`'s own drift-check precedent).
    No filesystem read occurs.
    """
    generated = generate(seed=SEED)
    return generated.to_csv_text().encode("utf-8")


def create_analysis(store: AnalysisStore) -> Analysis:
    """Create a new `QUEUED` analysis over the bundled demo dataset and
    store it. Does not run the pipeline — see `run_analysis`.
    """
    content = _generate_demo_content()
    content_hash = hashlib.sha256(content).hexdigest()
    byte_size = len(content)
    now = datetime.now(UTC)

    dataset = Dataset(
        dataset_id=str(uuid.uuid4()),
        original_filename=_DEMO_ORIGINAL_FILENAME,
        stored_filename=_DEMO_ORIGINAL_FILENAME,
        format=DatasetFormat.CSV,
        byte_size=byte_size,
        content_hash=content_hash,
        selected_worksheet=None,
        created_at=now,
        deleted_at=None,
        storage_location=_DEMO_STORAGE_LOCATION,
        source_type=DatasetSourceType.BUNDLED_DEMO,
    )
    analysis = Analysis(
        analysis_id=str(uuid.uuid4()),
        dataset=dataset,
        state=AnalysisState.QUEUED,
        security_exposure=_NO_EXPOSURE,
        dataset_profile=None,
        findings=(),
        priority_scores=(),
        trust_assessment=None,
        failure=None,
        created_at=now,
        started_at=None,
        completed_at=None,
        failed_at=None,
        cancelled_at=None,
    )
    store.add(analysis)
    return analysis


def run_analysis(
    store: AnalysisStore, analysis_id: str, *, now: datetime | None = None
) -> Analysis:
    """Run the full pipeline for a `QUEUED` analysis, transitioning it
    through `VALIDATING`/`PARSING`/`PROFILING`/`DETECTING` to `COMPLETED`.

    Idempotent: calling this on a non-`QUEUED` analysis returns the
    current `Analysis` unchanged without re-executing anything. Any
    exception raised while running the pipeline is isolated into a fixed,
    safe `FAILED` transition (never raising itself), matching `DET-01`
    `engine.py`'s own exception-isolation precedent.

    `now` is an optional injected reference instant (defaults to the real
    wall clock): both `compute_dataset_profile`'s `as_of` date and
    `run_detectors`' `analysis_timestamp` are derived from the same
    `now` value so a single call is internally consistent, and so tests
    can reproduce a fixed instant deterministically — the same
    reasoning `compute_dataset_profile` itself already documents for its
    own `as_of` parameter.

    Raises `AnalysisNotFoundError` for an unknown `analysis_id`.
    """
    analysis = store.get(analysis_id)
    if analysis is None:
        raise AnalysisNotFoundError(analysis_id)
    if analysis.state is not AnalysisState.QUEUED:
        return analysis

    effective_now = now if now is not None else datetime.now(UTC)
    started_at = datetime.now(UTC)

    try:
        content = _generate_demo_content()
        parsed = parse_csv(content)
        columns = parsed.parsed_dataset.columns

        dataset_profile = compute_dataset_profile(
            columns,
            parsed.rows,
            parsed.parsed_dataset.sampling,
            as_of=effective_now.date(),
        )
        mapping_rows = tuple(
            {column.internal_key: row[column.ordinal] for column in columns} for row in parsed.rows
        )
        results = run_detectors(
            list(DETECTORS),
            dataset_profile=dataset_profile,
            rows=mapping_rows,
            row_references=parsed.parsed_dataset.row_references,
            confirmed_context=None,
            security_exposure=analysis.security_exposure,
            analysis_timestamp=effective_now,
        )
        findings = tuple(finding for result in results for finding in result.findings)
        priority_scores = calculate_finding_priority_scores(
            findings, dataset_profile=dataset_profile
        )
        trust_assessment = calculate_trust_assessment(
            findings, priority_scores, security_exposure=analysis.security_exposure
        )
    except Exception:  # noqa: BLE001 - isolated per DET-01 engine.py precedent
        failed_at = datetime.now(UTC)
        failed = replace(
            analysis,
            state=AnalysisState.FAILED,
            failure=AnalysisFailure(code=_FAILURE_CODE, message=_FAILURE_MESSAGE),
            started_at=started_at,
            failed_at=failed_at,
        )
        store.replace(failed)
        return failed

    completed_at = datetime.now(UTC)
    completed = replace(
        analysis,
        state=AnalysisState.COMPLETED,
        dataset_profile=dataset_profile,
        findings=findings,
        priority_scores=priority_scores,
        trust_assessment=trust_assessment,
        started_at=started_at,
        completed_at=completed_at,
    )
    store.replace(completed)
    return completed


def get_status(store: AnalysisStore, analysis_id: str) -> Analysis:
    """Return the current `Analysis` for `analysis_id`.

    Raises `AnalysisNotFoundError` for an unknown ID.
    """
    analysis = store.get(analysis_id)
    if analysis is None:
        raise AnalysisNotFoundError(analysis_id)
    return analysis


def get_profile(store: AnalysisStore, analysis_id: str) -> DatasetProfile | None:
    """Return the `DatasetProfile` for a `COMPLETED` analysis, `None` for
    a known but not-yet-`COMPLETED` analysis.

    Raises `AnalysisNotFoundError` for an unknown ID.
    """
    return get_status(store, analysis_id).dataset_profile


def get_findings(store: AnalysisStore, analysis_id: str) -> tuple[FindingCandidate, ...]:
    """Return the findings tuple for a `COMPLETED` analysis, an empty
    tuple for a known but not-yet-`COMPLETED` analysis.

    Raises `AnalysisNotFoundError` for an unknown ID.
    """
    return get_status(store, analysis_id).findings


def cancel_analysis(store: AnalysisStore, analysis_id: str) -> Analysis:
    """Cancel a `QUEUED` analysis, transitioning it to `CANCELLED`.

    For any other known state, returns the `Analysis` unchanged (no
    exception) — `cancel_analysis` is only effective while `QUEUED`; true
    mid-pipeline cancellation requires real bounded background execution
    (`JOB-01`, not yet built).

    Raises `AnalysisNotFoundError` for an unknown ID.
    """
    analysis = store.get(analysis_id)
    if analysis is None:
        raise AnalysisNotFoundError(analysis_id)
    if analysis.state is not AnalysisState.QUEUED:
        return analysis

    cancelled_at = datetime.now(UTC)
    cancelled = replace(analysis, state=AnalysisState.CANCELLED, cancelled_at=cancelled_at)
    store.replace(cancelled)
    return cancelled
