// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AiProvenanceResponse
 *
 * Human-readable provenance of an accepted AI interpretation
 * (`AI-08`), derived by `ai_provider.display`.
 *
 * Only display labels and a sanitized identifier: never a filesystem
 * path (the raw configured model value never leaves the backend).
 * `model_identifier` is the final path segment only, bounded, kept for
 * diagnostics.
 */
export type AiProvenanceResponse = {
    /**
     * Deployment Label
     */
    deployment_label: string;
    /**
     * Model Identifier
     */
    model_identifier: string | null;
    /**
     * Model Label
     */
    model_label: string | null;
    /**
     * Quantization
     */
    quantization: string | null;
    /**
     * Runtime Label
     */
    runtime_label: string;
};

/**
 * AiStatusResponse
 */
export type AiStatusResponse = {
    /**
     * Assistance
     */
    assistance: 'off' | 'on';
    /**
     * Location
     */
    location: 'none' | 'local' | 'unknown';
    /**
     * Model Label
     */
    model_label: string | null;
    /**
     * Provider Label
     */
    provider_label: string;
    /**
     * Runtime Label
     */
    runtime_label: string | null;
    /**
     * Sample Values Sent
     */
    sample_values_sent: boolean;
    /**
     * State
     */
    state: 'disabled' | 'ready' | 'unavailable';
    /**
     * Summary
     */
    summary: string;
};

/**
 * AnalysisFailureResponse
 *
 * Mirrors `analysis.service.AnalysisFailure` — a fixed, safe,
 * non-leaking failure description. Never contains raw exception text.
 */
export type AnalysisFailureResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AnalysisHistoryItem
 */
export type AnalysisHistoryItem = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Byte Size
     */
    byte_size: number;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finding Count
     */
    finding_count: number | null;
    /**
     * Format
     */
    format: 'csv' | 'xlsx';
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Selected Worksheet
     */
    selected_worksheet: string | null;
    /**
     * Source
     */
    source: 'upload' | 'demo';
    /**
     * State
     */
    state: 'queued' | 'validating' | 'parsing' | 'profiling' | 'detecting' | 'completed' | 'failed' | 'cancelled';
    /**
     * Trust Label
     */
    trust_label: string | null;
};

/**
 * AnalysisHistoryResponse
 */
export type AnalysisHistoryResponse = {
    /**
     * Items
     */
    items: Array<AnalysisHistoryItem>;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AnalysisProfileResponse
 *
 * Body for `GET /analyses/{analysis_id}/profile`, mirroring
 * `profiling.schemas.DatasetProfile` (`docs/api-specification.md` §8).
 *
 * Deliberately omits §8's documented "include technical metrics" /
 * column paging / column-filter query options and the large
 * representative-value payload exclusion — this package returns the
 * full profile every time; filtering/paging is deferred to a later,
 * separate package once a real need is demonstrated (disclosed
 * Non-goal, not a silent omission).
 */
export type AnalysisProfileResponse = {
    /**
     * Column Profiles
     */
    column_profiles: Array<ColumnProfileResponse>;
    /**
     * Dataset Metrics
     */
    dataset_metrics: {
        [key: string]: unknown;
    };
    sampling: SampleMetadataResponse;
    /**
     * Schema Version
     */
    schema_version: string;
    timing: ProfilingTimingResponse;
    /**
     * Warnings
     */
    warnings: Array<WarningResponse>;
};

/**
 * AnalysisResource
 *
 * Body for `GET /analyses/{analysis_id}`, `POST .../cancel`, and the
 * `analysis` field of `POST /demo/sales`'s response
 * (`docs/api-specification.md` §6's documented "metadata, state,
 * dataset summary, timestamps, failure details" shape, narrowed to
 * what `API-01`'s in-memory engine actually tracks).
 *
 * `finding_count` is a convenience summary count; the full findings
 * list is served separately by `GET .../findings` (`docs/
 * api-specification.md`'s own list-endpoint-separation convention).
 */
export type AnalysisResource = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Cancelled At
     */
    cancelled_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    dataset: DatasetSummaryResponse;
    /**
     * Failed At
     */
    failed_at: string | null;
    failure: AnalysisFailureResponse | null;
    /**
     * Finding Count
     */
    finding_count: number;
    /**
     * Retry Source Analysis Id
     */
    retry_source_analysis_id?: string | null;
    security_exposure: SecurityExposureResponse;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * State
     */
    state: string;
    trust_assessment: TrustAssessmentResponse | null;
};

/**
 * AnalysisStatusResponse
 *
 * Body for `GET /analyses/{analysis_id}/status` — a lightweight
 * polling endpoint (`docs/api-specification.md` §6).
 *
 * `state` now reflects real, persisted stage progression
 * (`queued`/`parsing`/`profiling`/`detecting`/terminal — `JOB-01`,
 * `WP-075`: a bounded worker pool runs the pipeline in the background
 * instead of synchronously inside the request). `poll_interval_ms`
 * stays a fixed constant regardless (no adaptive backoff has been
 * built). `retryable` is `true` if and only if `state` is `failed`
 * (`JOB-01` slice 2, `WP-076`: `POST .../retry` exists now, restricted
 * to `FAILED` per `docs/product-requirements.md`'s "retry failed
 * work"). A numeric `progress_percentage` remains deliberately
 * omitted: there is no meaningful sub-stage partial-progress signal
 * within one stage — a disclosed, permanent non-goal, not a follow-up
 * slice.
 */
export type AnalysisStatusResponse = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Cancellable
     */
    cancellable: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Poll Interval Ms
     */
    poll_interval_ms: number;
    /**
     * Retryable
     */
    retryable: boolean;
    /**
     * State
     */
    state: string;
};

/**
 * AnalysisSummaryResponse
 *
 * Body for `GET /analyses/{analysis_id}/summary` (`UX-04`, D-070).
 *
 * Counts only: no cell value, no row-number list and no content hash.
 * `rows_affected` is the number of *distinct* rows that at least one finding
 * points at; `findings_without_row_detail` is how many findings name no row
 * (for example a whole-column finding), so rows affected is never read as
 * "every other row is clean".
 */
export type AnalysisSummaryResponse = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Column Count
     */
    column_count: number;
    completeness: CompletenessResponse;
    /**
     * Findings Total
     */
    findings_total: number;
    /**
     * Findings Without Row Detail
     */
    findings_without_row_detail: number;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Rows Affected
     */
    rows_affected: number;
};

/**
 * AnswerGuidedQuestionRequest
 *
 * Request body for `POST .../questions/{question_id}/answer`
 * (`UI-02` slice 2, `WP-064`).
 */
export type AnswerGuidedQuestionRequest = {
    /**
     * Answer Text
     */
    answer_text: string;
    /**
     * Expected Version
     */
    expected_version: number;
};

/**
 * AnswerGuidedQuestionResponse
 *
 * Body for `POST /analyses/{analysis_id}/questions/{question_id}/answer`
 * (`UI-02` slice 2, `WP-064`; `docs/api-specification.md` §9's "stores
 * an answer and resulting context updates").
 */
export type AnswerGuidedQuestionResponse = {
    answer: ClarificationAnswerResponse;
    context: ContextResponse;
    question: ClarificationQuestionResponse;
};

/**
 * Body_post_analysis_upload_api_v1_analyses_post
 */
export type BodyPostAnalysisUploadApiV1AnalysesPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Worksheet
     */
    worksheet?: string | null;
};

/**
 * Body_post_staged_upload_api_v1_staged_uploads_post
 */
export type BodyPostStagedUploadApiV1StagedUploadsPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BusinessImpactStatementResponse
 *
 * One *potential* business implication of a finding (`AI-08`),
 * mirroring `domain.explanation.BusinessImpactStatement`.
 *
 * `basis` is derived by TrustTable and says how a client must present the
 * statement: `"confirmed_context"` (it cites context the user confirmed or
 * corrected, so show it as *informed by* that context) or `"assumption"`
 * (only a possible consequence). Either way it is a potential impact shown
 * together with its `assumption` (the condition under which it would
 * hold), never as a fact — there is deliberately no "evidence" basis,
 * because the deterministic evidence establishes what was found in the
 * data, not what it costs a business.
 */
export type BusinessImpactStatementResponse = {
    /**
     * Assumption
     */
    assumption: string;
    /**
     * Basis
     */
    basis: 'confirmed_context' | 'assumption';
    /**
     * Context Fields
     */
    context_fields: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Statement
     */
    statement: string;
};

/**
 * ClarificationAnswerResponse
 *
 * Mirrors `domain.clarification.ClarificationAnswer` (`UI-02`
 * slice 2, `WP-064`).
 */
export type ClarificationAnswerResponse = {
    /**
     * Answered Timestamp
     */
    answered_timestamp: string;
    /**
     * Provenance
     */
    provenance: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Resulting Context Changes
     */
    resulting_context_changes: Array<string>;
    /**
     * Selected Answer Or Free Text
     */
    selected_answer_or_free_text: string;
};

/**
 * ClarificationQuestionListResponse
 *
 * Body for `GET /analyses/{analysis_id}/questions` (`UI-02`
 * slice 2, `WP-064`).
 */
export type ClarificationQuestionListResponse = {
    /**
     * Items
     */
    items: Array<ClarificationQuestionResponse>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * ClarificationQuestionResponse
 *
 * Mirrors `domain.clarification.ClarificationQuestion` (`UI-02`
 * slice 2, `WP-064`).
 */
export type ClarificationQuestionResponse = {
    /**
     * Affected Assumptions
     */
    affected_assumptions: Array<string>;
    /**
     * Answered State
     */
    answered_state: string;
    /**
     * Concise Text
     */
    concise_text: string;
    /**
     * Context Field
     */
    context_field: string;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Free Text Allowed
     */
    free_text_allowed: boolean;
    /**
     * Inferred Default
     */
    inferred_default: string | null;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Suggested Answers
     */
    suggested_answers: Array<string>;
};

/**
 * ColumnProfileResponse
 *
 * Mirrors `profiling.schemas.ColumnProfile`.
 *
 * `metrics` values are already JSON-safe primitives (str/int/float/
 * bool/None; e.g. date metrics are pre-formatted `.isoformat()`
 * strings) — `PROF-03`'s own established convention, reused unchanged.
 */
export type ColumnProfileResponse = {
    column: ColumnReferenceResponse;
    /**
     * Distinct Count
     */
    distinct_count: number;
    /**
     * Inferred Type
     */
    inferred_type: string;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    };
    /**
     * Null Count
     */
    null_count: number;
    /**
     * Warnings
     */
    warnings: Array<WarningResponse>;
};

/**
 * ColumnReferenceResponse
 *
 * Mirrors `domain.value_objects.ColumnReference`.
 */
export type ColumnReferenceResponse = {
    /**
     * Internal Key
     */
    internal_key: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Original Name
     */
    original_name: string;
};

/**
 * CompletenessResponse
 *
 * Missing values across the profiled cells (`UX-04`, D-070).
 *
 * `scope` is `"full"` or `"sampled"` as the profile recorded it, so the
 * interface never states a sampled figure as if it covered every row.
 * `missing_share` is `null` when there are no cells to measure.
 */
export type CompletenessResponse = {
    /**
     * Cells Missing
     */
    cells_missing: number;
    /**
     * Cells Total
     */
    cells_total: number;
    /**
     * Missing Share
     */
    missing_share: number | null;
    /**
     * Population Size
     */
    population_size: number;
    /**
     * Sample Size
     */
    sample_size: number;
    /**
     * Scope
     */
    scope: 'full' | 'sampled';
};

/**
 * ConfirmContextFieldsRequest
 *
 * Request body for `PUT /analyses/{analysis_id}/context` (`UI-02`
 * slice 2, `WP-064`). `edits` keys are `ContextField` string values
 * (e.g. `"probable_domain"`); an unknown key or a role-field key both
 * resolve to `INVALID_CONTEXT` (422).
 */
export type ConfirmContextFieldsRequest = {
    /**
     * Edits
     */
    edits: {
        [key: string]: string;
    };
    /**
     * Expected Version
     */
    expected_version: number;
};

/**
 * ConfirmedRelationshipModel
 *
 * A relationship: its current version and its full ordered history.
 */
export type ConfirmedRelationshipModel = {
    /**
     * Check Status
     */
    check_status: string;
    current: RelationshipVersionModel;
    /**
     * History
     */
    history: Array<RelationshipVersionModel>;
    /**
     * Kind
     */
    kind: string;
    /**
     * Relationship Id
     */
    relationship_id: string;
    /**
     * State
     */
    state: string;
};

/**
 * ConfirmedRelationshipRequest
 *
 * Body for `POST /analyses/{analysis_id}/confirmed-relationships`.
 *
 * `confirm` carries `start` and `end` only. `replace` carries
 * `relationship_id`, `expected_version`, `start` and `end`. `withdraw`
 * carries `relationship_id` and `expected_version` only.
 */
export type ConfirmedRelationshipRequest = {
    /**
     * End
     */
    end?: string | null;
    /**
     * Expected Version
     */
    expected_version?: number | null;
    /**
     * Kind
     */
    kind: 'start_end_date';
    /**
     * Relationship Id
     */
    relationship_id?: string | null;
    /**
     * Source
     */
    source?: 'direct' | 'suggestion';
    /**
     * Start
     */
    start?: string | null;
    /**
     * Transition
     */
    transition: 'confirm' | 'replace' | 'withdraw';
};

/**
 * ConfirmedRelationshipWriteResponse
 *
 * Result of one write.
 *
 * `check_status` states whether a check exists for the relationship. The
 * set of values is open and additive: a client treats an unknown value as
 * opaque. `not_active` means no check exists to run and never means the
 * data passed one.
 */
export type ConfirmedRelationshipWriteResponse = {
    /**
     * Check Status
     */
    check_status: string;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Relationship Id
     */
    relationship_id: string;
    /**
     * State
     */
    state: string;
    /**
     * Version
     */
    version: number;
};

/**
 * ConfirmedRelationshipsResponse
 *
 * Body for `GET /analyses/{analysis_id}/confirmed-relationships`.
 */
export type ConfirmedRelationshipsResponse = {
    /**
     * Relationships
     */
    relationships: Array<ConfirmedRelationshipModel>;
};

/**
 * ContextFieldValueResponse
 *
 * Mirrors `domain.context.ContextFieldValue` (`UI-02` slice 2,
 * `WP-064`). `value` is a plain `str` for the five single-value
 * `ContextField`s and a `list[str]` of column original names for the
 * four column-role fields — mirroring the domain type's own disclosed
 * open-typed shape exactly (see its docstring).
 */
export type ContextFieldValueResponse = {
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confirmation State
     */
    confirmation_state: string;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Inference Source
     */
    inference_source: string;
    /**
     * Value
     */
    value: string | Array<string>;
};

/**
 * ContextResponse
 *
 * Body for `GET`/`PUT /analyses/{analysis_id}/context` (`UI-02`
 * slice 2, `WP-064`; `docs/api-specification.md` §9).
 *
 * `context_version` is not part of `domain.context.DatasetContext`
 * itself (`Analysis.context_version` is separate) — included here as
 * a disclosed, minimal API-shape addition the client needs for the
 * optimistic-concurrency contract §9 already specifies ("requires
 * resource version"). Every other field mirrors `DatasetContext`
 * exactly.
 */
export type ContextResponse = {
    business_dates: ContextFieldValueResponse;
    candidate_keys: ContextFieldValueResponse;
    /**
     * Context Version
     */
    context_version: number;
    currency_behavior: ContextFieldValueResponse;
    dimensions: ContextFieldValueResponse;
    expected_business_rules: ContextFieldValueResponse;
    measure_roles: ContextFieldValueResponse;
    primary_entity: ContextFieldValueResponse;
    probable_domain: ContextFieldValueResponse;
    row_grain: ContextFieldValueResponse;
    /**
     * Schema Version
     */
    schema_version: string;
};

/**
 * CreateReportRequest
 *
 * Body for `POST /analyses/{analysis_id}/reports`.
 */
export type CreateReportRequest = {
    options?: ReportOptionsModel;
};

/**
 * CreateValidationRuleRequest
 *
 * Request body for `POST /analyses/{analysis_id}/rules` (`RULE-01`,
 * all 11 rule types as of slice 2, `WP-079`). `column_names` are
 * matched against the dataset's real `original_name` values; an
 * unknown name is rejected with `UNKNOWN_RULE_COLUMN` (422) before any
 * execution. Every parameter field not required by `rule_type`
 * (`docs/domain-model.md` §18's table, mirrored in
 * `domain.rules.ValidationRule`'s own docstring) must be left `null` —
 * a mismatch is rejected with `INVALID_RULE_PARAMETERS` (422).
 * `comparison_operator`/`condition_operator` are one of
 * `domain.rules.ComparisonOperator`'s closed string values.
 * `source_finding_id` (`RULE-02` slice 1, `WP-080`) is optional: when
 * given, the finding must exist on this analysis (`FINDING_NOT_FOUND`,
 * 404, otherwise) and the persisted rule records
 * `provenance="detector_generated"` with `source_finding_ids` set —
 * accepting a `GET .../rule-proposal` offer. Omitted (the default)
 * means `provenance="user_authored"`, unchanged from `RULE-01`.
 */
export type CreateValidationRuleRequest = {
    /**
     * Accepted Values
     */
    accepted_values?: Array<string> | null;
    /**
     * Column Names
     */
    column_names: Array<string>;
    /**
     * Comparison Operator
     */
    comparison_operator?: string | null;
    /**
     * Comparison Value
     */
    comparison_value?: number | null;
    /**
     * Condition Operator
     */
    condition_operator?: string | null;
    /**
     * Condition Value
     */
    condition_value?: number | null;
    /**
     * Description
     */
    description: string;
    /**
     * Maximum
     */
    maximum?: number | null;
    /**
     * Maximum Date
     */
    maximum_date?: string | null;
    /**
     * Minimum
     */
    minimum?: number | null;
    /**
     * Minimum Date
     */
    minimum_date?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Null Handling
     */
    null_handling?: string;
    /**
     * Pattern
     */
    pattern?: string | null;
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Source Finding Id
     */
    source_finding_id?: string | null;
    /**
     * Threshold Percentage
     */
    threshold_percentage?: number | null;
    /**
     * Tolerance
     */
    tolerance?: number | null;
};

/**
 * DatasetSummaryResponse
 *
 * A bounded summary of `domain.parsing.Dataset` — omits
 * `stored_filename`/`storage_location`/`deleted_at`, which are
 * internal storage facts. `selected_worksheet` (`ING-03`) is the name of
 * the worksheet an `xlsx` analysis was run over, and is `None` for CSV.
 */
export type DatasetSummaryResponse = {
    /**
     * Byte Size
     */
    byte_size: number;
    /**
     * Content Hash
     */
    content_hash: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Dataset Id
     */
    dataset_id: string;
    /**
     * Format
     */
    format: string;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Selected Worksheet
     */
    selected_worksheet?: string | null;
    /**
     * Source Type
     */
    source_type: string;
};

/**
 * DemoAnalysisResponse
 *
 * Body for `POST /demo/sales` (`docs/api-specification.md` §5:
 * "analysis resource" + "status URL").
 */
export type DemoAnalysisResponse = {
    analysis: AnalysisResource;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * FinalizeContextRequest
 *
 * Request body for `POST /analyses/{analysis_id}/finalize` (`UI-02`
 * slice 2, `WP-064`).
 */
export type FinalizeContextRequest = {
    /**
     * Expected Version
     */
    expected_version: number;
};

/**
 * FindingDetailResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}`
 * (`WP-027`, a disclosed bounded subset of `docs/api-specification.md`
 * §10's full documented finding-detail shape and
 * `docs/ui-specification.md` §4.7's "Finding detail" screen sections).
 *
 * Exposes exactly what is genuinely computable today: observation,
 * affected columns/rows, evidence count, technical metadata, security
 * exposure, and (`REV-01`, `WP-083`) review state. Deliberately omits
 * possible business impact, remediation, and proposed validation
 * rules, which live in their own dedicated endpoints
 * (`GET .../explanation`, `GET .../rule-proposal`), not this body.
 * `review_state`/`note`/`dismissal_reason`/`reviewed_at` default to
 * `"unreviewed"`/`null`/`null`/`null` for a finding with no recorded
 * review.
 *
 * `affected_row_numbers` (`FIND-01`, `WP-038`, extending) is a small,
 * disclosed addition: the finding's own affected `RowReference.row_number`
 * values, ascending. Needed by the Finding Detail UI's row-context
 * Prev/Next jump list (`docs/decision-log.md` D-025,
 * `project-ops/changes/CHG-001-investigation-ux-row-context.md` §3),
 * which cannot be built from `affected_row_count` alone. Every other
 * field is unchanged from `WP-027`.
 */
export type FindingDetailResponse = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Affected Row Numbers
     */
    affected_row_numbers: Array<number>;
    /**
     * Calculated Observation
     */
    calculated_observation: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Detector Id
     */
    detector_id: string;
    /**
     * Detector Version
     */
    detector_version: string;
    /**
     * Dismissal Reason
     */
    dismissal_reason: string | null;
    /**
     * Evidence Count
     */
    evidence_count: number;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Priority Score
     */
    priority_score: number;
    /**
     * Review State
     */
    review_state: string;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    security_exposure: SecurityExposureResponse;
    /**
     * Severity
     */
    severity: string;
};

/**
 * FindingEvidenceItem
 *
 * One entry in `GET .../findings/{finding_id}/evidence`'s response
 * (`WP-027`). Mirrors `domain.evidence.Evidence`, deliberately
 * excluding `structured_payload`: `docs/domain-model.md` §13's own
 * invariants ("report references use display-safe summaries"; raw
 * sensitive values are not embedded unless explicitly allowed, a
 * redaction guarantee not yet mechanically enforced pending `PRIV-01`)
 * both argue against exposing the open-ended raw payload through any
 * API response before that redaction package exists.
 * `affected_row_count` is a bounded count, matching `FindingItem`'s
 * established convention and `docs/domain-model.md` §13's "row
 * evidence is bounded for display" invariant — not the raw row
 * reference list.
 */
export type FindingEvidenceItem = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Display Safe Summary
     */
    display_safe_summary: string;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Evidence Type
     */
    evidence_type: string;
    /**
     * Scope
     */
    scope: string;
};

/**
 * FindingEvidenceListResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/evidence`.
 * Returns an empty `items` list (not an error) if a valid finding
 * happens to have no resolvable evidence entries — defensive, matching
 * `FindingsListResponse`'s existing empty-list-not-an-error convention.
 */
export type FindingEvidenceListResponse = {
    /**
     * Items
     */
    items: Array<FindingEvidenceItem>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * FindingExplanationResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/explanation`
 * (`UI-02` slice 1, `WP-063`; four-section analysis `AI-08`). Mirrors
 * `domain.explanation.FindingExplanation` exactly, plus `ai_call_status`
 * (`WP-065`, defect fix) and the human-readable `ai_provenance`.
 * `provenance` is the `Provenance` enum's string value
 * (`"deterministic_fallback"` or `"ai_interpretation"` only —
 * `FindingExplanation`'s own closed set, `AI-05`).
 * `provider_name`/`model_identifier` are both `null` for a
 * deterministic-fallback explanation (no provider was used — the
 * default, AI-disabled behavior) and populated for an accepted
 * AI-interpretation explanation. **`AI-08`:** `model_identifier` is the
 * *sanitized* identifier (final path segment only); the raw configured
 * value never leaves the backend, and `ai_provenance` carries the labels
 * a UI should show.
 *
 * **`AI-08` — the four sections.** `narrative` (the explanation),
 * `business_impact`, `remediation` and `validation_rule` are always
 * present. When `provenance == "ai_interpretation"` they come from one
 * validated, structurally constrained AI response; otherwise from
 * TrustTable's deterministic built-in guidance, so they are useful with
 * AI disabled, rejected or failing. `business_impact` statements carry
 * their `basis`; `remediation` is advisory only (TrustTable never
 * changes an uploaded file); `validation_rule.status` is always
 * `"proposed"`.
 *
 * `ai_call_status` (`WP-065`) discloses this specific request's own AI
 * call lifecycle independently of `provenance`/`provider_name`, closing
 * a real gap `provenance` alone cannot express: `provenance ==
 * "deterministic_fallback"` is ambiguous between "no provider is
 * configured" and "a provider was tried and failed/was rejected".
 * Exactly one of:
 *
 * - `"not_configured"` — `Settings.llm_provider == "disabled"`; no AI
 * call was attempted for this request.
 * - `"attempted_accepted"` — a provider was called and its output was
 * accepted; `provenance == "ai_interpretation"`.
 * - `"attempted_rejected"` — a provider was called, its output (and
 * any bounded retries) failed `ai_boundary.validation.
 * validate_model_output`; the deterministic explanation was returned
 * instead (`provenance == "deterministic_fallback"`).
 * - `"attempted_provider_error"` — a provider was called and raised a
 * `ProviderError` (connection/timeout/malformed response); the
 * deterministic explanation was returned instead (`provenance ==
 * "deterministic_fallback"`).
 *
 * Deliberately independent of `Analysis.security_exposure` (`GET
 * .../findings/{finding_id}`'s own `security_exposure` field), which
 * describes only the deterministic detection pipeline's own,
 * permanently-`False` raw-sample-exposure posture — never this
 * per-request enrichment call. See `docs/architecture.md` §6/§7 and
 * `docs/decision-log.md` D-037/D-038.
 *
 * `evidence_sent_to_model`/`confirmed_context_sent_to_model`
 * (`WP-065` r4 — closes a real semantic-review `FAIL`: `ai_call_status`
 * alone discloses axes 1-3/6 of D-038's six-axis model but never
 * axis 5, "finding/evidence/context metadata exposure") disclose
 * exactly what bounded metadata this specific request actually sent
 * to a model, independent of whether that attempt was accepted.
 * `evidence_sent_to_model` is `True` whenever `ai_call_status` is any
 * `attempted_*` value (this finding's own captured `Evidence` is
 * always the envelope's `computed_evidence` on every attempt).
 * `confirmed_context_sent_to_model` is `True` only when an attempt was
 * made *and* `Analysis.context_finalized` was already `True` at call
 * time (the same gate `confirmed_context` itself uses). Both are
 * `False` whenever `ai_call_status == "not_configured"`. Neither ever
 * reflects raw dataset sample content — only this route's own bounded
 * `Evidence`/`DatasetContext` inputs, matching `AI-05`/`CTX-02`'s
 * existing zero-raw-sample-sending design.
 */
export type FindingExplanationResponse = {
    /**
     * Ai Call Status
     */
    ai_call_status: string;
    ai_provenance: AiProvenanceResponse | null;
    /**
     * Business Impact
     */
    business_impact: Array<BusinessImpactStatementResponse>;
    /**
     * Confirmed Context Sent To Model
     */
    confirmed_context_sent_to_model: boolean;
    /**
     * Evidence Sent To Model
     */
    evidence_sent_to_model: boolean;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Model Identifier
     */
    model_identifier: string | null;
    /**
     * Narrative
     */
    narrative: string;
    /**
     * Provenance
     */
    provenance: string;
    /**
     * Provider Name
     */
    provider_name: string | null;
    /**
     * Referenced Columns
     */
    referenced_columns: Array<ColumnReferenceResponse>;
    /**
     * Referenced Evidence Ids
     */
    referenced_evidence_ids: Array<string>;
    /**
     * Remediation
     */
    remediation: Array<RemediationOptionResponse>;
    validation_rule: ProposedValidationRuleResponse | null;
};

/**
 * FindingItem
 *
 * One entry in `GET /analyses/{analysis_id}/findings`'s response
 * (`docs/api-specification.md` §10's documented list-item shape,
 * narrowed to what `API-01`'s `FindingCandidate` actually carries).
 *
 * `finding_id` (`WP-027`) is a stringified zero-based index into the
 * analysis's own findings tuple — a disclosed, reversible interim
 * scheme (see `analysis.service.get_finding`); no full persisted
 * identifier exists yet. `review_state`/`note`/`dismissal_reason`/
 * `reviewed_at` (`REV-01`, `WP-083`) default to `"unreviewed"`/`null`/
 * `null`/`null` for a finding with no recorded review.
 * `affected_row_count` and `evidence_count` are bounded counts, not the
 * raw row-reference/evidence-ID lists — matching this repository's
 * established "bounded, not raw" list-response convention (`PROF-03`'s
 * profile endpoint precedent above).
 */
export type FindingItem = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Calculated Observation
     */
    calculated_observation: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Detector Id
     */
    detector_id: string;
    /**
     * Detector Version
     */
    detector_version: string;
    /**
     * Dismissal Reason
     */
    dismissal_reason: string | null;
    /**
     * Evidence Count
     */
    evidence_count: number;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Priority Score
     */
    priority_score: number;
    /**
     * Review State
     */
    review_state: string;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    /**
     * Severity
     */
    severity: string;
};

/**
 * FindingReviewRequest
 *
 * Body for `PUT /analyses/{analysis_id}/findings/{finding_id}/review`
 * (`REV-01`, `WP-083`). `dismissal_reason` is required (and must be
 * non-empty) when `state` is `"dismissed"`, and must be omitted/`null`
 * otherwise — `422 REVIEW_INVALID` on either violation.
 */
export type FindingReviewRequest = {
    /**
     * Dismissal Reason
     */
    dismissal_reason?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * State
     */
    state: string;
};

/**
 * FindingReviewResponse
 *
 * Body for `PUT .../review`'s response, and the shape
 * `FindingItem`/`FindingDetailResponse`'s own review fields mirror.
 */
export type FindingReviewResponse = {
    /**
     * Dismissal Reason
     */
    dismissal_reason: string | null;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Review State
     */
    review_state: string;
    /**
     * Reviewed At
     */
    reviewed_at: string;
};

/**
 * FindingsListResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings`. Returns an empty
 * `items` list (not an error) for a known, not-yet-`COMPLETED`
 * analysis — matching `analysis.service.get_findings`'s own documented
 * behavior exactly.
 */
export type FindingsListResponse = {
    /**
     * Items
     */
    items: Array<FindingItem>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 *
 * A single named readiness check entry.
 */
export type HealthCheck = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'failing' | 'not_configured';
};

/**
 * LivenessResponse
 *
 * Body for `GET /api/v1/health/live`.
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status?: 'alive';
};

/**
 * ObservationItem
 *
 * One neutral observation in `GET /analyses/{analysis_id}/observations`
 * (`DET-03` closure package 2, `WP-109`; provisional API).
 *
 * Mirrors `domain.observation.Observation`. It deliberately has **no**
 * severity, confidence, priority or review field: an observation is not a
 * finding and never affects the trust score or priority. `structured_payload`
 * is excluded, like `FindingEvidenceItem`'s, so no open-ended raw payload is
 * exposed; `summary` already states the counts. `affected_row_numbers` are
 * the bounded example row numbers (at most 20), never cell values.
 * `kind` is the closed kind name (`value_evidence` is the only one today); a
 * later kind is added, never a change to this one.
 */
export type ObservationItem = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Numbers
     */
    affected_row_numbers: Array<number>;
    /**
     * Kind
     */
    kind: string;
    /**
     * Observation Id
     */
    observation_id: string;
    /**
     * Producer Detector Id
     */
    producer_detector_id: string;
    /**
     * Scope
     */
    scope: string;
    /**
     * Summary
     */
    summary: string;
};

/**
 * ObservationsListResponse
 *
 * Body for `GET /analyses/{analysis_id}/observations`. Read-only. Returns
 * an empty `items` list (not an error) for a known analysis that is not
 * `COMPLETED` or that has no observations, matching
 * `FindingsListResponse`'s convention.
 */
export type ObservationsListResponse = {
    /**
     * Items
     */
    items: Array<ObservationItem>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * PreviousAnalysisNoticeResponse
 *
 * `same_file`: the staged bytes match a completed analysis exactly.
 * `same_name`: only the file name matches; no diff is implied.
 */
export type PreviousAnalysisNoticeResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Kind
     */
    kind: 'same_file' | 'same_name';
    /**
     * Latest Analysed At
     */
    latest_analysed_at: string;
    /**
     * Latest Analysis Id
     */
    latest_analysis_id: string;
    /**
     * Latest Filename
     */
    latest_filename: string;
};

/**
 * ProfilingTimingResponse
 *
 * Mirrors `profiling.schemas.ProfilingTiming`.
 */
export type ProfilingTimingResponse = {
    /**
     * Completed At
     */
    completed_at: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Started At
     */
    started_at: string;
};

/**
 * ProposedValidationRuleResponse
 *
 * A validation rule *proposal* (`AI-08`), mirroring
 * `domain.explanation.ProposedValidationRule`.
 *
 * `status` is always `"proposed"`: nothing in the application runs,
 * enforces or exports this rule (the rule engine is `RULE-01`, a later
 * item), so a client must never present it as active or authoritative.
 * `rule_type` is one of the `docs/product-requirements.md` §13 types.
 */
export type ProposedValidationRuleResponse = {
    /**
     * Columns
     */
    columns: Array<ColumnReferenceResponse>;
    /**
     * Description
     */
    description: string;
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Status
     */
    status: 'proposed';
};

/**
 * ReadinessResponse
 *
 * Body for `GET /api/v1/health/ready`.
 *
 * `status` is `"ready"` iff every entry in `checks` has `status: "ok"`.
 */
export type ReadinessResponse = {
    /**
     * Checks
     */
    checks: Array<HealthCheck>;
    /**
     * Status
     */
    status: 'ready' | 'not_ready';
};

/**
 * RelationshipVersionModel
 *
 * One immutable version. The version number and `recorded_at` are set by
 * the server; `source` is the client's own assertion (`direct` or
 * `suggestion`) and is not verified provenance. There is no identity field.
 */
export type RelationshipVersionModel = {
    end: RoleColumnModel;
    /**
     * Kind
     */
    kind: string;
    /**
     * Recorded At
     */
    recorded_at: string;
    /**
     * Relationship Id
     */
    relationship_id: string;
    /**
     * Source
     */
    source: string;
    start: RoleColumnModel;
    /**
     * State
     */
    state: string;
    /**
     * Transition
     */
    transition: string;
    /**
     * Version
     */
    version: number;
};

/**
 * RemediationOptionResponse
 *
 * One structured remediation recommendation (`REM-01`), mirroring
 * `domain.explanation.RemediationOption`.
 *
 * `risk_warning` is always populated (never `null`/empty) — a documented
 * simplification of `docs/domain-model.md` §16's conditional "destructive
 * actions include risk warnings" invariant, avoiding fragile keyword-based
 * destructiveness classification. `technical_example` is `null` when no
 * concrete example applies. Advisory only — TrustTable never changes
 * uploaded data; nothing here claims that it did.
 */
export type RemediationOptionResponse = {
    /**
     * Action Summary
     */
    action_summary: string;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Historical Correction Guidance
     */
    historical_correction_guidance: string;
    /**
     * Remediation Id
     */
    remediation_id: string;
    /**
     * Responsible Role
     */
    responsible_role: string;
    /**
     * Risk Warning
     */
    risk_warning: string;
    /**
     * Source System Prevention Guidance
     */
    source_system_prevention_guidance: string;
    /**
     * Technical Example
     */
    technical_example: string | null;
    /**
     * Urgency
     */
    urgency: string;
    /**
     * Verification Step
     */
    verification_step: string;
};

/**
 * ReportListResponse
 *
 * Body for `GET /analyses/{analysis_id}/reports`.
 */
export type ReportListResponse = {
    /**
     * Reports
     */
    reports: Array<ReportResponse>;
};

/**
 * ReportOptionsModel
 *
 * The three report options; each defaults to off.
 */
export type ReportOptionsModel = {
    /**
     * Include Bounded Examples
     */
    include_bounded_examples?: boolean;
    /**
     * Include Dismissed
     */
    include_dismissed?: boolean;
    /**
     * Include Technical Appendix
     */
    include_technical_appendix?: boolean;
};

/**
 * ReportResponse
 *
 * Metadata of one generated report snapshot.
 */
export type ReportResponse = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Generated At
     */
    generated_at: string;
    options: ReportOptionsModel;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Schema Version
     */
    schema_version: string;
};

/**
 * RetryAnalysisResponse
 *
 * Body for `POST /analyses/{analysis_id}/retry` (`JOB-01` slice 2,
 * `WP-076`; `docs/api-specification.md` §6: "202 Accepted, new attempt
 * ID or updated attempt resource"), resolved as a new, independent
 * `Analysis` — `analysis.analysis_id` is the "new attempt ID";
 * `retry_source_analysis_id` echoes the original analysis that was
 * retried, for a client that only has the response body (also visible
 * via `AnalysisResource.retry_source_analysis_id` on any later `GET`).
 */
export type RetryAnalysisResponse = {
    analysis: AnalysisResource;
    /**
     * Retry Source Analysis Id
     */
    retry_source_analysis_id: string;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * RoleColumnModel
 *
 * A role's `ColumnReference` identity: the internal key and ordinal.
 */
export type RoleColumnModel = {
    /**
     * Internal Key
     */
    internal_key: string;
    /**
     * Ordinal
     */
    ordinal: number;
};

/**
 * RowContextEntryResponse
 *
 * One row in a `RowContextResponse` window (`FIND-01`, `WP-038`).
 * Mirrors `domain.row_context.RowContextEntry`. `values` is positional,
 * aligned by index with the owning response's `columns` list — not a
 * mapping, matching the domain type's own alignment convention.
 * `source_line_number`/`fingerprint` are omitted: `parsers.csv_parser`
 * never sets either on the `RowReference`s it produces today, so
 * exposing them would only ever be `null` — a disclosed, reversible
 * scoping choice, not a contract gap.
 */
export type RowContextEntryResponse = {
    /**
     * Is Affected By Finding
     */
    is_affected_by_finding: boolean;
    /**
     * Is Anchor
     */
    is_anchor: boolean;
    /**
     * Row Number
     */
    row_number: number;
    /**
     * Values
     */
    values: Array<string | null>;
};

/**
 * RowContextResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/row-context`
 * (`FIND-01`, `WP-038`; `docs/api-specification.md` §10; `docs/domain-model.md`
 * §13's "Row context (non-Evidence)" subsection). Mirrors
 * `domain.row_context.RowContextWindow` exactly.
 */
export type RowContextResponse = {
    /**
     * Actual After
     */
    actual_after: number;
    /**
     * Actual Before
     */
    actual_before: number;
    /**
     * Columns
     */
    columns: Array<ColumnReferenceResponse>;
    /**
     * Max Window
     */
    max_window: number;
    /**
     * Requested After
     */
    requested_after: number;
    /**
     * Requested Before
     */
    requested_before: number;
    /**
     * Rows
     */
    rows: Array<RowContextEntryResponse>;
    /**
     * Truncated At End
     */
    truncated_at_end: boolean;
    /**
     * Truncated At Start
     */
    truncated_at_start: boolean;
};

/**
 * RuleExecutionResultResponse
 *
 * Mirrors `domain.rules.RuleExecutionResult` (`RULE-01` slice 1,
 * `docs/domain-model.md` §19). `MAX_MISSING_PERCENTAGE`/
 * `MAX_DUPLICATE_PERCENTAGE` report the raw incident count per row —
 * compare `fail_count / (pass_count + fail_count)` against the rule's
 * own `threshold_percentage` for the intended pass/fail interpretation.
 */
export type RuleExecutionResultResponse = {
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Error
     */
    error: string | null;
    /**
     * Example Failures
     */
    example_failures: Array<RuleFailureExampleResponse>;
    /**
     * Executed At
     */
    executed_at: string;
    /**
     * Fail Count
     */
    fail_count: number;
    /**
     * Pass Count
     */
    pass_count: number;
    /**
     * Skipped Count
     */
    skipped_count: number;
};

/**
 * RuleFailureExampleResponse
 *
 * Mirrors `domain.rules.RuleFailureExample` — one bounded example of
 * a row that failed a rule (`RULE-01` slice 1).
 */
export type RuleFailureExampleResponse = {
    /**
     * Reason
     */
    reason: string;
    /**
     * Row Number
     */
    row_number: number;
};

/**
 * RuleProposalResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/
 * rule-proposal` (`RULE-02` slice 1, `WP-080`; AI-assisted extension,
 * slice 2, `WP-081`). `available=False` means no safe proposal exists
 * for this finding's detector (`reason` states why); `rule`/`result`
 * are then both `null`. `available=True` means `rule` is an
 * already-executed candidate, never persisted by this route —
 * `rule.rule_id` is a fresh, disposable id, not a stored identity.
 * Accepting the offer is a separate `POST .../rules` call with
 * `source_finding_id` set; `rule.provenance` distinguishes
 * `"detector_generated"` (slice 1, no AI involved) from
 * `"ai_assisted"` (slice 2, this response's own AI attempt was
 * accepted).
 *
 * `ai_call_status`/`evidence_sent_to_model` (`WP-081`) mirror
 * `FindingExplanationResponse`'s own established disclosure fields
 * exactly, scoped to this specific request's AI-assisted attempt (for
 * `consistency.inconsistent_capitalization` only, and only once slice
 * 1's deterministic mapping already reported unavailable):
 *
 * - `"not_configured"` — no AI-assisted attempt was made for this
 * request, either because `Settings.llm_provider == "disabled"` or
 * because this finding's detector is not AI-assistable (including
 * every case where slice 1 already found a deterministic mapping).
 * - `"attempted_accepted"` — a provider was called and its chosen
 * value was accepted; `rule.provenance == "ai_assisted"`.
 * - `"attempted_rejected"` — a provider was called, but its output
 * failed `ai_boundary.rule_generation.validate_rule_generation_output`;
 * falls back to slice 1's identical `available=False` response.
 * - `"attempted_provider_error"` — a provider was called and raised a
 * `ProviderError`; falls back to slice 1's identical
 * `available=False` response.
 *
 * `evidence_sent_to_model` is `True` whenever `ai_call_status` is any
 * `attempted_*` value (this finding's own evidence is always the
 * envelope's `computed_evidence` on every attempt); `False` otherwise.
 * Never reflects raw dataset sample content — this contract sends
 * zero dataset samples regardless.
 */
export type RuleProposalResponse = {
    /**
     * Ai Call Status
     */
    ai_call_status: string;
    /**
     * Available
     */
    available: boolean;
    /**
     * Evidence Sent To Model
     */
    evidence_sent_to_model: boolean;
    /**
     * Reason
     */
    reason: string | null;
    result: RuleExecutionResultResponse | null;
    rule: ValidationRuleResponse | null;
};

/**
 * SampleMetadataResponse
 *
 * Mirrors `domain.parsing.SampleMetadata`.
 */
export type SampleMetadataResponse = {
    /**
     * Method
     */
    method: string | null;
    /**
     * Population Size
     */
    population_size: number;
    /**
     * Sample Size
     */
    sample_size: number;
    /**
     * Scope
     */
    scope: string;
};

/**
 * SecurityExposureResponse
 *
 * Mirrors `detectors.contract.SecurityExposureState` exactly —
 * see that class's own docstring for the full scope boundary
 * (`WP-065`, defect fix; `docs/decision-log.md` D-038). Always reports
 * the disabled/no-transmission state today: not because no AI/LLM
 * provider exists (`AI-01`/`AI-02`/`AI-03` are all real and can be
 * configured), but because this field describes only the
 * deterministic detection pipeline's own raw-sample-exposure posture,
 * which never sends dataset content to a model. It is deliberately
 * independent of, and must never be conflated with, a separate,
 * optional, per-request AI enrichment call's own status (see
 * `FindingExplanationResponse.ai_call_status`).
 */
export type SecurityExposureResponse = {
    /**
     * Model Provider Enabled
     */
    model_provider_enabled: boolean;
    /**
     * Sample Transmission Enabled
     */
    sample_transmission_enabled: boolean;
};

/**
 * StagedCheckGroup
 */
export type StagedCheckGroup = {
    /**
     * Description
     */
    description: string;
    /**
     * Title
     */
    title: string;
};

/**
 * StagedNotice
 */
export type StagedNotice = {
    /**
     * Code
     */
    code: string;
    /**
     * Count
     */
    count: number;
    /**
     * Message
     */
    message: string;
};

/**
 * StagedProblem
 */
export type StagedProblem = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * StagedShape
 */
export type StagedShape = {
    /**
     * Column Count
     */
    column_count: number;
    /**
     * Row Count
     */
    row_count: number;
};

/**
 * StagedUploadInspectRequest
 */
export type StagedUploadInspectRequest = {
    /**
     * Staging Ref
     */
    staging_ref: string;
    /**
     * Worksheet
     */
    worksheet?: string | null;
};

/**
 * StagedUploadReference
 *
 * A request body naming one staged upload.
 */
export type StagedUploadReference = {
    /**
     * Staging Ref
     */
    staging_ref: string;
};

/**
 * StagedUploadResponse
 */
export type StagedUploadResponse = {
    /**
     * Byte Size
     */
    byte_size: number;
    /**
     * Can Run
     */
    can_run: boolean;
    /**
     * Checks
     */
    checks: Array<StagedCheckGroup>;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Format
     */
    format: 'csv' | 'xlsx';
    /**
     * Notices
     */
    notices: Array<StagedNotice>;
    previously_analysed?: PreviousAnalysisNoticeResponse | null;
    /**
     * Problems
     */
    problems: Array<StagedProblem>;
    /**
     * Selected Worksheet
     */
    selected_worksheet: string | null;
    shape: StagedShape | null;
    /**
     * Staging Ref
     */
    staging_ref: string | null;
    /**
     * Worksheets
     */
    worksheets: Array<StagedWorksheet> | null;
};

/**
 * StagedUploadRunRequest
 */
export type StagedUploadRunRequest = {
    /**
     * Staging Ref
     */
    staging_ref: string;
    /**
     * Worksheet
     */
    worksheet?: string | null;
};

/**
 * StagedWorksheet
 */
export type StagedWorksheet = {
    /**
     * Name
     */
    name: string;
    /**
     * Visible
     */
    visible: boolean;
};

/**
 * TrustAssessmentResponse
 *
 * Mirrors `risk.scoring.TrustAssessment`.
 */
export type TrustAssessmentResponse = {
    /**
     * Finding Count
     */
    finding_count: number;
    /**
     * Highest Priority Score
     */
    highest_priority_score: number | null;
    /**
     * Label
     */
    label: string;
    /**
     * Score
     */
    score: number;
};

/**
 * UploadAnalysisResponse
 *
 * Body for `POST /analyses` (`WP-029`; `docs/api-specification.md`
 * §6's disclosed subset: "analysis resource" + "status URL" — the
 * same shape as `DemoAnalysisResponse`, kept as its own type for a
 * distinct generated client function name).
 */
export type UploadAnalysisResponse = {
    analysis: AnalysisResource;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValidationRuleResponse
 *
 * Mirrors `domain.rules.ValidationRule` (`RULE-01`, all 11 rule
 * types as of slice 2, `WP-079`; `docs/domain-model.md` §18). Every
 * parameter field not used by `rule_type` is `null` — the same shape
 * `ValidationRule.__post_init__` itself enforces.
 */
export type ValidationRuleResponse = {
    /**
     * Accepted Values
     */
    accepted_values: Array<string> | null;
    /**
     * Columns
     */
    columns: Array<ColumnReferenceResponse>;
    /**
     * Comparison Operator
     */
    comparison_operator: string | null;
    /**
     * Comparison Value
     */
    comparison_value: number | null;
    /**
     * Condition Operator
     */
    condition_operator: string | null;
    /**
     * Condition Value
     */
    condition_value: number | null;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled: boolean;
    last_result: RuleExecutionResultResponse | null;
    /**
     * Maximum
     */
    maximum: number | null;
    /**
     * Maximum Date
     */
    maximum_date: string | null;
    /**
     * Minimum
     */
    minimum: number | null;
    /**
     * Minimum Date
     */
    minimum_date: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Null Handling
     */
    null_handling: string;
    /**
     * Pattern
     */
    pattern: string | null;
    /**
     * Provenance
     */
    provenance: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Rule Type
     */
    rule_type: string;
    /**
     * Schema Version
     */
    schema_version: string;
    /**
     * Scope
     */
    scope: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Source Finding Ids
     */
    source_finding_ids: Array<string>;
    /**
     * Threshold Percentage
     */
    threshold_percentage: number | null;
    /**
     * Tolerance
     */
    tolerance: number | null;
};

/**
 * ValidationRulesListResponse
 *
 * Body for `GET /analyses/{analysis_id}/rules` (`RULE-01`).
 */
export type ValidationRulesListResponse = {
    /**
     * Items
     */
    items: Array<ValidationRuleResponse>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * VersionResponse
 *
 * Body for `GET /api/v1/version`. Always returned with HTTP 200.
 */
export type VersionResponse = {
    /**
     * Api Version
     */
    api_version: string;
    /**
     * Application Version
     */
    application_version: string;
    /**
     * Build Commit
     */
    build_commit?: string | null;
    /**
     * Detector Catalogue Version
     */
    detector_catalogue_version?: string | null;
    /**
     * Environment Mode
     */
    environment_mode: 'development' | 'test' | 'production';
    /**
     * Schema Version
     */
    schema_version?: string | null;
};

/**
 * WarningResponse
 *
 * Mirrors the shared shape of `domain.parsing.ParsingWarning`,
 * `profiling.schemas.ProfilingWarning`, and `detectors.contract.DetectorWarning`
 * (namespaced `code`, `message`, optional column reference).
 */
export type WarningResponse = {
    /**
     * Code
     */
    code: string;
    column?: ColumnReferenceResponse | null;
    /**
     * Message
     */
    message: string;
};

export type GetAiStatusApiV1AiStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/status';
};

export type GetAiStatusApiV1AiStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AiStatusResponse;
};

export type GetAiStatusApiV1AiStatusGetResponse = GetAiStatusApiV1AiStatusGetResponses[keyof GetAiStatusApiV1AiStatusGetResponses];

export type GetAnalysisHistoryApiV1AnalysesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/analyses';
};

export type GetAnalysisHistoryApiV1AnalysesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisHistoryApiV1AnalysesGetError = GetAnalysisHistoryApiV1AnalysesGetErrors[keyof GetAnalysisHistoryApiV1AnalysesGetErrors];

export type GetAnalysisHistoryApiV1AnalysesGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisHistoryResponse;
};

export type GetAnalysisHistoryApiV1AnalysesGetResponse = GetAnalysisHistoryApiV1AnalysesGetResponses[keyof GetAnalysisHistoryApiV1AnalysesGetResponses];

export type PostAnalysisUploadApiV1AnalysesPostData = {
    body: BodyPostAnalysisUploadApiV1AnalysesPost;
    path?: never;
    query?: never;
    url: '/api/v1/analyses';
};

export type PostAnalysisUploadApiV1AnalysesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisUploadApiV1AnalysesPostError = PostAnalysisUploadApiV1AnalysesPostErrors[keyof PostAnalysisUploadApiV1AnalysesPostErrors];

export type PostAnalysisUploadApiV1AnalysesPostResponses = {
    /**
     * Successful Response
     */
    202: UploadAnalysisResponse;
};

export type PostAnalysisUploadApiV1AnalysesPostResponse = PostAnalysisUploadApiV1AnalysesPostResponses[keyof PostAnalysisUploadApiV1AnalysesPostResponses];

export type DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}';
};

export type DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteError = DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteErrors[keyof DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteErrors];

export type DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteResponse = DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteResponses[keyof DeleteAnalysisResourceApiV1AnalysesAnalysisIdDeleteResponses];

export type GetAnalysisApiV1AnalysesAnalysisIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}';
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetError = GetAnalysisApiV1AnalysesAnalysisIdGetErrors[keyof GetAnalysisApiV1AnalysesAnalysisIdGetErrors];

export type GetAnalysisApiV1AnalysesAnalysisIdGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResource;
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetResponse = GetAnalysisApiV1AnalysesAnalysisIdGetResponses[keyof GetAnalysisApiV1AnalysesAnalysisIdGetResponses];

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/cancel';
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostError = PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors[keyof PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors];

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResource;
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponse = PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses[keyof PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses];

export type ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/confirmed-relationships';
};

export type ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetError = ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetErrors[keyof ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetErrors];

export type ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetResponses = {
    /**
     * Successful Response
     */
    200: ConfirmedRelationshipsResponse;
};

export type ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetResponse = ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetResponses[keyof ListConfirmedRelationshipsApiV1AnalysesAnalysisIdConfirmedRelationshipsGetResponses];

export type WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostData = {
    body: ConfirmedRelationshipRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/confirmed-relationships';
};

export type WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostError = WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostErrors[keyof WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostErrors];

export type WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostResponses = {
    /**
     * OK
     */
    200: ConfirmedRelationshipWriteResponse;
    /**
     * Successful Response
     */
    201: ConfirmedRelationshipWriteResponse;
};

export type WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostResponse = WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostResponses[keyof WriteConfirmedRelationshipApiV1AnalysesAnalysisIdConfirmedRelationshipsPostResponses];

export type GetAnalysisContextApiV1AnalysesAnalysisIdContextGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/context';
};

export type GetAnalysisContextApiV1AnalysesAnalysisIdContextGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisContextApiV1AnalysesAnalysisIdContextGetError = GetAnalysisContextApiV1AnalysesAnalysisIdContextGetErrors[keyof GetAnalysisContextApiV1AnalysesAnalysisIdContextGetErrors];

export type GetAnalysisContextApiV1AnalysesAnalysisIdContextGetResponses = {
    /**
     * Successful Response
     */
    200: ContextResponse;
};

export type GetAnalysisContextApiV1AnalysesAnalysisIdContextGetResponse = GetAnalysisContextApiV1AnalysesAnalysisIdContextGetResponses[keyof GetAnalysisContextApiV1AnalysesAnalysisIdContextGetResponses];

export type PutAnalysisContextApiV1AnalysesAnalysisIdContextPutData = {
    body: ConfirmContextFieldsRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/context';
};

export type PutAnalysisContextApiV1AnalysesAnalysisIdContextPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutAnalysisContextApiV1AnalysesAnalysisIdContextPutError = PutAnalysisContextApiV1AnalysesAnalysisIdContextPutErrors[keyof PutAnalysisContextApiV1AnalysesAnalysisIdContextPutErrors];

export type PutAnalysisContextApiV1AnalysesAnalysisIdContextPutResponses = {
    /**
     * Successful Response
     */
    200: ContextResponse;
};

export type PutAnalysisContextApiV1AnalysesAnalysisIdContextPutResponse = PutAnalysisContextApiV1AnalysesAnalysisIdContextPutResponses[keyof PutAnalysisContextApiV1AnalysesAnalysisIdContextPutResponses];

export type GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/exports/rules.json';
};

export type GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetError = GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetErrors[keyof GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetErrors];

export type GetRulesExportJsonApiV1AnalysesAnalysisIdExportsRulesJsonGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/exports/rules.yaml';
};

export type GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetError = GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetErrors[keyof GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetErrors];

export type GetRulesExportYamlApiV1AnalysesAnalysisIdExportsRulesYamlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostData = {
    body: FinalizeContextRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/finalize';
};

export type PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostError = PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostErrors[keyof PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostErrors];

export type PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostResponses = {
    /**
     * Successful Response
     */
    202: AnalysisResource;
};

export type PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostResponse = PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostResponses[keyof PostAnalysisFinalizeApiV1AnalysesAnalysisIdFinalizePostResponses];

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings';
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetError = GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors[keyof GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors];

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses = {
    /**
     * Successful Response
     */
    200: FindingsListResponse;
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponse = GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses[keyof GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses];

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}';
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetError = GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors[keyof GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors];

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses = {
    /**
     * Successful Response
     */
    200: FindingDetailResponse;
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponse = GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses[keyof GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses];

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/evidence';
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetError = GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors[keyof GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors];

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses = {
    /**
     * Successful Response
     */
    200: FindingEvidenceListResponse;
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponse = GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses[keyof GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses];

export type GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/explanation';
};

export type GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetError = GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetErrors[keyof GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetErrors];

export type GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetResponses = {
    /**
     * Successful Response
     */
    200: FindingExplanationResponse;
};

export type GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetResponse = GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetResponses[keyof GetAnalysisFindingExplanationApiV1AnalysesAnalysisIdFindingsFindingIdExplanationGetResponses];

export type PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutData = {
    body: FindingReviewRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/review';
};

export type PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutError = PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutErrors[keyof PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutErrors];

export type PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutResponses = {
    /**
     * Successful Response
     */
    200: FindingReviewResponse;
};

export type PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutResponse = PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutResponses[keyof PutAnalysisFindingReviewApiV1AnalysesAnalysisIdFindingsFindingIdReviewPutResponses];

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query: {
        /**
         * Anchor Row
         */
        anchor_row: number;
        /**
         * Before
         */
        before?: number;
        /**
         * After
         */
        after?: number;
    };
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/row-context';
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetError = GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors[keyof GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors];

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses = {
    /**
     * Successful Response
     */
    200: RowContextResponse;
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponse = GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses[keyof GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses];

export type GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/rule-proposal';
};

export type GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetError = GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetErrors[keyof GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetErrors];

export type GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetResponses = {
    /**
     * Successful Response
     */
    200: RuleProposalResponse;
};

export type GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetResponse = GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetResponses[keyof GetAnalysisFindingRuleProposalApiV1AnalysesAnalysisIdFindingsFindingIdRuleProposalGetResponses];

export type GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/observations';
};

export type GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetError = GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetErrors[keyof GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetErrors];

export type GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetResponses = {
    /**
     * Successful Response
     */
    200: ObservationsListResponse;
};

export type GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetResponse = GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetResponses[keyof GetAnalysisObservationsApiV1AnalysesAnalysisIdObservationsGetResponses];

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/profile';
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetError = GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors[keyof GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors];

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisProfileResponse;
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponse = GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses[keyof GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses];

export type GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/questions';
};

export type GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetError = GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetErrors[keyof GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetErrors];

export type GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: ClarificationQuestionListResponse;
};

export type GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetResponse = GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetResponses[keyof GetAnalysisQuestionsApiV1AnalysesAnalysisIdQuestionsGetResponses];

export type PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostData = {
    body: AnswerGuidedQuestionRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/questions/{question_id}/answer';
};

export type PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostError = PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostErrors[keyof PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostErrors];

export type PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostResponses = {
    /**
     * Successful Response
     */
    200: AnswerGuidedQuestionResponse;
};

export type PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostResponse = PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostResponses[keyof PostAnalysisQuestionAnswerApiV1AnalysesAnalysisIdQuestionsQuestionIdAnswerPostResponses];

export type ListReportsApiV1AnalysesAnalysisIdReportsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/reports';
};

export type ListReportsApiV1AnalysesAnalysisIdReportsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListReportsApiV1AnalysesAnalysisIdReportsGetError = ListReportsApiV1AnalysesAnalysisIdReportsGetErrors[keyof ListReportsApiV1AnalysesAnalysisIdReportsGetErrors];

export type ListReportsApiV1AnalysesAnalysisIdReportsGetResponses = {
    /**
     * Successful Response
     */
    200: ReportListResponse;
};

export type ListReportsApiV1AnalysesAnalysisIdReportsGetResponse = ListReportsApiV1AnalysesAnalysisIdReportsGetResponses[keyof ListReportsApiV1AnalysesAnalysisIdReportsGetResponses];

export type CreateReportApiV1AnalysesAnalysisIdReportsPostData = {
    /**
     * Body
     */
    body?: CreateReportRequest | null;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/reports';
};

export type CreateReportApiV1AnalysesAnalysisIdReportsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReportApiV1AnalysesAnalysisIdReportsPostError = CreateReportApiV1AnalysesAnalysisIdReportsPostErrors[keyof CreateReportApiV1AnalysesAnalysisIdReportsPostErrors];

export type CreateReportApiV1AnalysesAnalysisIdReportsPostResponses = {
    /**
     * Successful Response
     */
    201: ReportResponse;
};

export type CreateReportApiV1AnalysesAnalysisIdReportsPostResponse = CreateReportApiV1AnalysesAnalysisIdReportsPostResponses[keyof CreateReportApiV1AnalysesAnalysisIdReportsPostResponses];

export type GetReportApiV1AnalysesAnalysisIdReportsReportIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/reports/{report_id}';
};

export type GetReportApiV1AnalysesAnalysisIdReportsReportIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportApiV1AnalysesAnalysisIdReportsReportIdGetError = GetReportApiV1AnalysesAnalysisIdReportsReportIdGetErrors[keyof GetReportApiV1AnalysesAnalysisIdReportsReportIdGetErrors];

export type GetReportApiV1AnalysesAnalysisIdReportsReportIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReportResponse;
};

export type GetReportApiV1AnalysesAnalysisIdReportsReportIdGetResponse = GetReportApiV1AnalysesAnalysisIdReportsReportIdGetResponses[keyof GetReportApiV1AnalysesAnalysisIdReportsReportIdGetResponses];

export type DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/reports/{report_id}/download';
};

export type DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetError = DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetErrors[keyof DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetErrors];

export type DownloadReportApiV1AnalysesAnalysisIdReportsReportIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rerun';
};

export type PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostError = PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostErrors[keyof PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostErrors];

export type PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostResponses = {
    /**
     * Successful Response
     */
    202: UploadAnalysisResponse;
};

export type PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostResponse = PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostResponses[keyof PostAnalysisRerunApiV1AnalysesAnalysisIdRerunPostResponses];

export type PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/retry';
};

export type PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostError = PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostErrors[keyof PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostErrors];

export type PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostResponses = {
    /**
     * Successful Response
     */
    202: RetryAnalysisResponse;
};

export type PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostResponse = PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostResponses[keyof PostAnalysisRetryApiV1AnalysesAnalysisIdRetryPostResponses];

export type GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rules';
};

export type GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetError = GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetErrors[keyof GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetErrors];

export type GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetResponses = {
    /**
     * Successful Response
     */
    200: ValidationRulesListResponse;
};

export type GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetResponse = GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetResponses[keyof GetAnalysisRulesApiV1AnalysesAnalysisIdRulesGetResponses];

export type PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostData = {
    body: CreateValidationRuleRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rules';
};

export type PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostError = PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostErrors[keyof PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostErrors];

export type PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostResponses = {
    /**
     * Successful Response
     */
    201: ValidationRuleResponse;
};

export type PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostResponse = PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostResponses[keyof PostAnalysisRuleApiV1AnalysesAnalysisIdRulesPostResponses];

export type DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rules/{rule_id}';
};

export type DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteError = DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteErrors[keyof DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteErrors];

export type DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteResponse = DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteResponses[keyof DeleteAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdDeleteResponses];

export type GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rules/{rule_id}';
};

export type GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetError = GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetErrors[keyof GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetErrors];

export type GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetResponses = {
    /**
     * Successful Response
     */
    200: ValidationRuleResponse;
};

export type GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetResponse = GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetResponses[keyof GetAnalysisRuleApiV1AnalysesAnalysisIdRulesRuleIdGetResponses];

export type PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/rules/{rule_id}/test';
};

export type PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostError = PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostErrors[keyof PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostErrors];

export type PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostResponses = {
    /**
     * Successful Response
     */
    200: ValidationRuleResponse;
};

export type PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostResponse = PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostResponses[keyof PostAnalysisRuleTestApiV1AnalysesAnalysisIdRulesRuleIdTestPostResponses];

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/status';
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetError = GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors[keyof GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors];

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisStatusResponse;
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponse = GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses[keyof GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses];

export type GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/summary';
};

export type GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetError = GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetErrors[keyof GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetErrors];

export type GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisSummaryResponse;
};

export type GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetResponse = GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetResponses[keyof GetAnalysisSummaryApiV1AnalysesAnalysisIdSummaryGetResponses];

export type PostDemoSalesApiV1DemoSalesPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo/sales';
};

export type PostDemoSalesApiV1DemoSalesPostResponses = {
    /**
     * Successful Response
     */
    202: DemoAnalysisResponse;
};

export type PostDemoSalesApiV1DemoSalesPostResponse = PostDemoSalesApiV1DemoSalesPostResponses[keyof PostDemoSalesApiV1DemoSalesPostResponses];

export type GetLivenessApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type GetLivenessApiV1HealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type GetLivenessApiV1HealthLiveGetResponse = GetLivenessApiV1HealthLiveGetResponses[keyof GetLivenessApiV1HealthLiveGetResponses];

export type GetReadinessApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type GetReadinessApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type GetReadinessApiV1HealthReadyGetResponse = GetReadinessApiV1HealthReadyGetResponses[keyof GetReadinessApiV1HealthReadyGetResponses];

export type PostStagedUploadApiV1StagedUploadsPostData = {
    body: BodyPostStagedUploadApiV1StagedUploadsPost;
    path?: never;
    query?: never;
    url: '/api/v1/staged-uploads';
};

export type PostStagedUploadApiV1StagedUploadsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostStagedUploadApiV1StagedUploadsPostError = PostStagedUploadApiV1StagedUploadsPostErrors[keyof PostStagedUploadApiV1StagedUploadsPostErrors];

export type PostStagedUploadApiV1StagedUploadsPostResponses = {
    /**
     * Successful Response
     */
    201: StagedUploadResponse;
};

export type PostStagedUploadApiV1StagedUploadsPostResponse = PostStagedUploadApiV1StagedUploadsPostResponses[keyof PostStagedUploadApiV1StagedUploadsPostResponses];

export type PostStagedUploadDiscardApiV1StagedUploadsDiscardPostData = {
    body: StagedUploadReference;
    path?: never;
    query?: never;
    url: '/api/v1/staged-uploads/discard';
};

export type PostStagedUploadDiscardApiV1StagedUploadsDiscardPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostStagedUploadDiscardApiV1StagedUploadsDiscardPostError = PostStagedUploadDiscardApiV1StagedUploadsDiscardPostErrors[keyof PostStagedUploadDiscardApiV1StagedUploadsDiscardPostErrors];

export type PostStagedUploadDiscardApiV1StagedUploadsDiscardPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PostStagedUploadDiscardApiV1StagedUploadsDiscardPostResponse = PostStagedUploadDiscardApiV1StagedUploadsDiscardPostResponses[keyof PostStagedUploadDiscardApiV1StagedUploadsDiscardPostResponses];

export type PostStagedUploadInspectApiV1StagedUploadsInspectPostData = {
    body: StagedUploadInspectRequest;
    path?: never;
    query?: never;
    url: '/api/v1/staged-uploads/inspect';
};

export type PostStagedUploadInspectApiV1StagedUploadsInspectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostStagedUploadInspectApiV1StagedUploadsInspectPostError = PostStagedUploadInspectApiV1StagedUploadsInspectPostErrors[keyof PostStagedUploadInspectApiV1StagedUploadsInspectPostErrors];

export type PostStagedUploadInspectApiV1StagedUploadsInspectPostResponses = {
    /**
     * Successful Response
     */
    200: StagedUploadResponse;
};

export type PostStagedUploadInspectApiV1StagedUploadsInspectPostResponse = PostStagedUploadInspectApiV1StagedUploadsInspectPostResponses[keyof PostStagedUploadInspectApiV1StagedUploadsInspectPostResponses];

export type PostStagedUploadRunApiV1StagedUploadsRunPostData = {
    body: StagedUploadRunRequest;
    path?: never;
    query?: never;
    url: '/api/v1/staged-uploads/run';
};

export type PostStagedUploadRunApiV1StagedUploadsRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostStagedUploadRunApiV1StagedUploadsRunPostError = PostStagedUploadRunApiV1StagedUploadsRunPostErrors[keyof PostStagedUploadRunApiV1StagedUploadsRunPostErrors];

export type PostStagedUploadRunApiV1StagedUploadsRunPostResponses = {
    /**
     * Successful Response
     */
    202: UploadAnalysisResponse;
};

export type PostStagedUploadRunApiV1StagedUploadsRunPostResponse = PostStagedUploadRunApiV1StagedUploadsRunPostResponses[keyof PostStagedUploadRunApiV1StagedUploadsRunPostResponses];

export type GetVersionApiV1VersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type GetVersionApiV1VersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type GetVersionApiV1VersionGetResponse = GetVersionApiV1VersionGetResponses[keyof GetVersionApiV1VersionGetResponses];
