// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HealthCheck
 *
 * A single named readiness check entry.
 */
export type HealthCheck = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'failing' | 'not_configured';
};

/**
 * LivenessResponse
 *
 * Body for `GET /api/v1/health/live`.
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status?: 'alive';
};

/**
 * ReadinessResponse
 *
 * Body for `GET /api/v1/health/ready`.
 *
 * `status` is `"ready"` iff every entry in `checks` has `status: "ok"`.
 */
export type ReadinessResponse = {
    /**
     * Checks
     */
    checks: Array<HealthCheck>;
    /**
     * Status
     */
    status: 'ready' | 'not_ready';
};

/**
 * VersionResponse
 *
 * Body for `GET /api/v1/version`. Always returned with HTTP 200.
 */
export type VersionResponse = {
    /**
     * Api Version
     */
    api_version: string;
    /**
     * Application Version
     */
    application_version: string;
    /**
     * Build Commit
     */
    build_commit?: string | null;
    /**
     * Detector Catalogue Version
     */
    detector_catalogue_version?: string | null;
    /**
     * Environment Mode
     */
    environment_mode: 'development' | 'test' | 'production';
    /**
     * Schema Version
     */
    schema_version?: string | null;
};

export type GetLivenessApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type GetLivenessApiV1HealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type GetLivenessApiV1HealthLiveGetResponse = GetLivenessApiV1HealthLiveGetResponses[keyof GetLivenessApiV1HealthLiveGetResponses];

export type GetReadinessApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type GetReadinessApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type GetReadinessApiV1HealthReadyGetResponse = GetReadinessApiV1HealthReadyGetResponses[keyof GetReadinessApiV1HealthReadyGetResponses];

export type GetVersionApiV1VersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type GetVersionApiV1VersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type GetVersionApiV1VersionGetResponse = GetVersionApiV1VersionGetResponses[keyof GetVersionApiV1VersionGetResponses];
