// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalysisFailureResponse
 *
 * Mirrors `analysis.service.AnalysisFailure` — a fixed, safe,
 * non-leaking failure description. Never contains raw exception text.
 */
export type AnalysisFailureResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AnalysisProfileResponse
 *
 * Body for `GET /analyses/{analysis_id}/profile`, mirroring
 * `profiling.schemas.DatasetProfile` (`docs/api-specification.md` §8).
 *
 * Deliberately omits §8's documented "include technical metrics" /
 * column paging / column-filter query options and the large
 * representative-value payload exclusion — this package returns the
 * full profile every time; filtering/paging is deferred to a later,
 * separate package once a real need is demonstrated (disclosed
 * Non-goal, not a silent omission).
 */
export type AnalysisProfileResponse = {
    /**
     * Column Profiles
     */
    column_profiles: Array<ColumnProfileResponse>;
    /**
     * Dataset Metrics
     */
    dataset_metrics: {
        [key: string]: unknown;
    };
    sampling: SampleMetadataResponse;
    /**
     * Schema Version
     */
    schema_version: string;
    timing: ProfilingTimingResponse;
    /**
     * Warnings
     */
    warnings: Array<WarningResponse>;
};

/**
 * AnalysisResource
 *
 * Body for `GET /analyses/{analysis_id}`, `POST .../cancel`, and the
 * `analysis` field of `POST /demo/sales`'s response
 * (`docs/api-specification.md` §6's documented "metadata, state,
 * dataset summary, timestamps, failure details" shape, narrowed to
 * what `API-01`'s in-memory engine actually tracks).
 *
 * `finding_count` is a convenience summary count; the full findings
 * list is served separately by `GET .../findings` (`docs/
 * api-specification.md`'s own list-endpoint-separation convention).
 */
export type AnalysisResource = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Cancelled At
     */
    cancelled_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    dataset: DatasetSummaryResponse;
    /**
     * Failed At
     */
    failed_at: string | null;
    failure: AnalysisFailureResponse | null;
    /**
     * Finding Count
     */
    finding_count: number;
    security_exposure: SecurityExposureResponse;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * State
     */
    state: string;
    trust_assessment: TrustAssessmentResponse | null;
};

/**
 * AnalysisStatusResponse
 *
 * Body for `GET /analyses/{analysis_id}/status` — a lightweight
 * polling endpoint (`docs/api-specification.md` §6).
 *
 * `poll_interval_ms` is a fixed constant: `run_analysis` executes
 * synchronously to completion within one call (`API-01` enabling
 * slice, `WP-023`), so there is no real progress signal to derive a
 * dynamic recommendation from yet (`JOB-01`, not yet built).
 * `retryable`/a numeric `progress_percentage` are deliberately omitted:
 * no retry endpoint exists yet, and synchronous execution has no
 * meaningful partial-progress signal either.
 */
export type AnalysisStatusResponse = {
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Cancellable
     */
    cancellable: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Poll Interval Ms
     */
    poll_interval_ms: number;
    /**
     * State
     */
    state: string;
};

/**
 * Body_post_analysis_upload_api_v1_analyses_post
 */
export type BodyPostAnalysisUploadApiV1AnalysesPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ColumnProfileResponse
 *
 * Mirrors `profiling.schemas.ColumnProfile`.
 *
 * `metrics` values are already JSON-safe primitives (str/int/float/
 * bool/None; e.g. date metrics are pre-formatted `.isoformat()`
 * strings) — `PROF-03`'s own established convention, reused unchanged.
 */
export type ColumnProfileResponse = {
    column: ColumnReferenceResponse;
    /**
     * Distinct Count
     */
    distinct_count: number;
    /**
     * Inferred Type
     */
    inferred_type: string;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: unknown;
    };
    /**
     * Null Count
     */
    null_count: number;
    /**
     * Warnings
     */
    warnings: Array<WarningResponse>;
};

/**
 * ColumnReferenceResponse
 *
 * Mirrors `domain.value_objects.ColumnReference`.
 */
export type ColumnReferenceResponse = {
    /**
     * Internal Key
     */
    internal_key: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Original Name
     */
    original_name: string;
};

/**
 * DatasetSummaryResponse
 *
 * A bounded summary of `domain.parsing.Dataset` — omits
 * `stored_filename`/`storage_location`/`selected_worksheet`/
 * `deleted_at`, none of which are meaningful yet for an in-memory,
 * demo-only, never-deleted dataset (`API-01` non-goals: no generic
 * upload, no deletion).
 */
export type DatasetSummaryResponse = {
    /**
     * Byte Size
     */
    byte_size: number;
    /**
     * Content Hash
     */
    content_hash: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Dataset Id
     */
    dataset_id: string;
    /**
     * Format
     */
    format: string;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Source Type
     */
    source_type: string;
};

/**
 * DemoAnalysisResponse
 *
 * Body for `POST /demo/sales` (`docs/api-specification.md` §5:
 * "analysis resource" + "status URL").
 */
export type DemoAnalysisResponse = {
    analysis: AnalysisResource;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * FindingDetailResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}`
 * (`WP-027`, a disclosed bounded subset of `docs/api-specification.md`
 * §10's full documented finding-detail shape and
 * `docs/ui-specification.md` §4.7's "Finding detail" screen sections).
 *
 * Exposes exactly what is genuinely computable today: observation,
 * affected columns/rows, evidence count, technical metadata, and
 * security exposure. Deliberately omits possible business impact,
 * remediation, proposed validation rules, and review state — no
 * package computes any of those yet (`REM-01`, `RULE-01`, `REV-01` are
 * all later, unimplemented backlog items); a placeholder field would
 * misrepresent "not built yet" as "computed but empty".
 *
 * `affected_row_numbers` (`FIND-01`, `WP-038`, extending) is a small,
 * disclosed addition: the finding's own affected `RowReference.row_number`
 * values, ascending. Needed by the Finding Detail UI's row-context
 * Prev/Next jump list (`docs/decision-log.md` D-025,
 * `project-ops/changes/CHG-001-investigation-ux-row-context.md` §3),
 * which cannot be built from `affected_row_count` alone. Every other
 * field is unchanged from `WP-027`.
 */
export type FindingDetailResponse = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Affected Row Numbers
     */
    affected_row_numbers: Array<number>;
    /**
     * Calculated Observation
     */
    calculated_observation: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Detector Id
     */
    detector_id: string;
    /**
     * Detector Version
     */
    detector_version: string;
    /**
     * Evidence Count
     */
    evidence_count: number;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Priority Score
     */
    priority_score: number;
    security_exposure: SecurityExposureResponse;
    /**
     * Severity
     */
    severity: string;
};

/**
 * FindingEvidenceItem
 *
 * One entry in `GET .../findings/{finding_id}/evidence`'s response
 * (`WP-027`). Mirrors `domain.evidence.Evidence`, deliberately
 * excluding `structured_payload`: `docs/domain-model.md` §13's own
 * invariants ("report references use display-safe summaries"; raw
 * sensitive values are not embedded unless explicitly allowed, a
 * redaction guarantee not yet mechanically enforced pending `PRIV-01`)
 * both argue against exposing the open-ended raw payload through any
 * API response before that redaction package exists.
 * `affected_row_count` is a bounded count, matching `FindingItem`'s
 * established convention and `docs/domain-model.md` §13's "row
 * evidence is bounded for display" invariant — not the raw row
 * reference list.
 */
export type FindingEvidenceItem = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Display Safe Summary
     */
    display_safe_summary: string;
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Evidence Type
     */
    evidence_type: string;
    /**
     * Scope
     */
    scope: string;
};

/**
 * FindingEvidenceListResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/evidence`.
 * Returns an empty `items` list (not an error) if a valid finding
 * happens to have no resolvable evidence entries — defensive, matching
 * `FindingsListResponse`'s existing empty-list-not-an-error convention.
 */
export type FindingEvidenceListResponse = {
    /**
     * Items
     */
    items: Array<FindingEvidenceItem>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * FindingItem
 *
 * One entry in `GET /analyses/{analysis_id}/findings`'s response
 * (`docs/api-specification.md` §10's documented list-item shape,
 * narrowed to what `API-01`'s `FindingCandidate` actually carries).
 *
 * `finding_id` (`WP-027`) is a stringified zero-based index into the
 * analysis's own findings tuple — a disclosed, reversible interim
 * scheme (see `analysis.service.get_finding`); no full persisted
 * identifier exists yet. No review-state field: the full `Finding`
 * aggregate's review state (`docs/domain-model.md` §12) does not exist
 * yet (`REV-01`, a later package). `affected_row_count` and
 * `evidence_count` are bounded counts, not the raw row-reference/
 * evidence-ID lists — matching this repository's established
 * "bounded, not raw" list-response convention (`PROF-03`'s profile
 * endpoint precedent above).
 */
export type FindingItem = {
    /**
     * Affected Columns
     */
    affected_columns: Array<ColumnReferenceResponse>;
    /**
     * Affected Row Count
     */
    affected_row_count: number;
    /**
     * Calculated Observation
     */
    calculated_observation: string;
    /**
     * Category
     */
    category: string;
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Detector Id
     */
    detector_id: string;
    /**
     * Detector Version
     */
    detector_version: string;
    /**
     * Evidence Count
     */
    evidence_count: number;
    /**
     * Finding Id
     */
    finding_id: string;
    /**
     * Priority Score
     */
    priority_score: number;
    /**
     * Severity
     */
    severity: string;
};

/**
 * FindingsListResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings`. Returns an empty
 * `items` list (not an error) for a known, not-yet-`COMPLETED`
 * analysis — matching `analysis.service.get_findings`'s own documented
 * behavior exactly.
 */
export type FindingsListResponse = {
    /**
     * Items
     */
    items: Array<FindingItem>;
    /**
     * Total Items
     */
    total_items: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 *
 * A single named readiness check entry.
 */
export type HealthCheck = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'failing' | 'not_configured';
};

/**
 * LivenessResponse
 *
 * Body for `GET /api/v1/health/live`.
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status?: 'alive';
};

/**
 * ProfilingTimingResponse
 *
 * Mirrors `profiling.schemas.ProfilingTiming`.
 */
export type ProfilingTimingResponse = {
    /**
     * Completed At
     */
    completed_at: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Started At
     */
    started_at: string;
};

/**
 * ReadinessResponse
 *
 * Body for `GET /api/v1/health/ready`.
 *
 * `status` is `"ready"` iff every entry in `checks` has `status: "ok"`.
 */
export type ReadinessResponse = {
    /**
     * Checks
     */
    checks: Array<HealthCheck>;
    /**
     * Status
     */
    status: 'ready' | 'not_ready';
};

/**
 * RowContextEntryResponse
 *
 * One row in a `RowContextResponse` window (`FIND-01`, `WP-038`).
 * Mirrors `domain.row_context.RowContextEntry`. `values` is positional,
 * aligned by index with the owning response's `columns` list — not a
 * mapping, matching the domain type's own alignment convention.
 * `source_line_number`/`fingerprint` are omitted: `parsers.csv_parser`
 * never sets either on the `RowReference`s it produces today, so
 * exposing them would only ever be `null` — a disclosed, reversible
 * scoping choice, not a contract gap.
 */
export type RowContextEntryResponse = {
    /**
     * Is Affected By Finding
     */
    is_affected_by_finding: boolean;
    /**
     * Is Anchor
     */
    is_anchor: boolean;
    /**
     * Row Number
     */
    row_number: number;
    /**
     * Values
     */
    values: Array<string | null>;
};

/**
 * RowContextResponse
 *
 * Body for `GET /analyses/{analysis_id}/findings/{finding_id}/row-context`
 * (`FIND-01`, `WP-038`; `docs/api-specification.md` §10; `docs/domain-model.md`
 * §13's "Row context (non-Evidence)" subsection). Mirrors
 * `domain.row_context.RowContextWindow` exactly.
 */
export type RowContextResponse = {
    /**
     * Actual After
     */
    actual_after: number;
    /**
     * Actual Before
     */
    actual_before: number;
    /**
     * Columns
     */
    columns: Array<ColumnReferenceResponse>;
    /**
     * Max Window
     */
    max_window: number;
    /**
     * Requested After
     */
    requested_after: number;
    /**
     * Requested Before
     */
    requested_before: number;
    /**
     * Rows
     */
    rows: Array<RowContextEntryResponse>;
    /**
     * Truncated At End
     */
    truncated_at_end: boolean;
    /**
     * Truncated At Start
     */
    truncated_at_start: boolean;
};

/**
 * SampleMetadataResponse
 *
 * Mirrors `domain.parsing.SampleMetadata`.
 */
export type SampleMetadataResponse = {
    /**
     * Method
     */
    method: string | null;
    /**
     * Population Size
     */
    population_size: number;
    /**
     * Sample Size
     */
    sample_size: number;
    /**
     * Scope
     */
    scope: string;
};

/**
 * SecurityExposureResponse
 *
 * Mirrors `detectors.contract.SecurityExposureState`. Always
 * reports the disabled/no-transmission state today — no AI/LLM
 * provider exists yet (`AI-01`/`AI-02`).
 */
export type SecurityExposureResponse = {
    /**
     * Model Provider Enabled
     */
    model_provider_enabled: boolean;
    /**
     * Sample Transmission Enabled
     */
    sample_transmission_enabled: boolean;
};

/**
 * TrustAssessmentResponse
 *
 * Mirrors `risk.scoring.TrustAssessment`.
 */
export type TrustAssessmentResponse = {
    /**
     * Finding Count
     */
    finding_count: number;
    /**
     * Highest Priority Score
     */
    highest_priority_score: number | null;
    /**
     * Label
     */
    label: string;
    /**
     * Score
     */
    score: number;
};

/**
 * UploadAnalysisResponse
 *
 * Body for `POST /analyses` (`WP-029`; `docs/api-specification.md`
 * §6's disclosed subset: "analysis resource" + "status URL" — the
 * same shape as `DemoAnalysisResponse`, kept as its own type for a
 * distinct generated client function name).
 */
export type UploadAnalysisResponse = {
    analysis: AnalysisResource;
    /**
     * Status Url
     */
    status_url: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersionResponse
 *
 * Body for `GET /api/v1/version`. Always returned with HTTP 200.
 */
export type VersionResponse = {
    /**
     * Api Version
     */
    api_version: string;
    /**
     * Application Version
     */
    application_version: string;
    /**
     * Build Commit
     */
    build_commit?: string | null;
    /**
     * Detector Catalogue Version
     */
    detector_catalogue_version?: string | null;
    /**
     * Environment Mode
     */
    environment_mode: 'development' | 'test' | 'production';
    /**
     * Schema Version
     */
    schema_version?: string | null;
};

/**
 * WarningResponse
 *
 * Mirrors the shared shape of `domain.parsing.ParsingWarning`,
 * `profiling.schemas.ProfilingWarning`, and `detectors.contract.DetectorWarning`
 * (namespaced `code`, `message`, optional column reference).
 */
export type WarningResponse = {
    /**
     * Code
     */
    code: string;
    column?: ColumnReferenceResponse | null;
    /**
     * Message
     */
    message: string;
};

export type PostAnalysisUploadApiV1AnalysesPostData = {
    body: BodyPostAnalysisUploadApiV1AnalysesPost;
    path?: never;
    query?: never;
    url: '/api/v1/analyses';
};

export type PostAnalysisUploadApiV1AnalysesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisUploadApiV1AnalysesPostError = PostAnalysisUploadApiV1AnalysesPostErrors[keyof PostAnalysisUploadApiV1AnalysesPostErrors];

export type PostAnalysisUploadApiV1AnalysesPostResponses = {
    /**
     * Successful Response
     */
    202: UploadAnalysisResponse;
};

export type PostAnalysisUploadApiV1AnalysesPostResponse = PostAnalysisUploadApiV1AnalysesPostResponses[keyof PostAnalysisUploadApiV1AnalysesPostResponses];

export type GetAnalysisApiV1AnalysesAnalysisIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}';
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetError = GetAnalysisApiV1AnalysesAnalysisIdGetErrors[keyof GetAnalysisApiV1AnalysesAnalysisIdGetErrors];

export type GetAnalysisApiV1AnalysesAnalysisIdGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResource;
};

export type GetAnalysisApiV1AnalysesAnalysisIdGetResponse = GetAnalysisApiV1AnalysesAnalysisIdGetResponses[keyof GetAnalysisApiV1AnalysesAnalysisIdGetResponses];

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/cancel';
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostError = PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors[keyof PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostErrors];

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResource;
};

export type PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponse = PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses[keyof PostAnalysisCancelApiV1AnalysesAnalysisIdCancelPostResponses];

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings';
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetError = GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors[keyof GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetErrors];

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses = {
    /**
     * Successful Response
     */
    200: FindingsListResponse;
};

export type GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponse = GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses[keyof GetAnalysisFindingsApiV1AnalysesAnalysisIdFindingsGetResponses];

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}';
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetError = GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors[keyof GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetErrors];

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses = {
    /**
     * Successful Response
     */
    200: FindingDetailResponse;
};

export type GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponse = GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses[keyof GetAnalysisFindingApiV1AnalysesAnalysisIdFindingsFindingIdGetResponses];

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/evidence';
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetError = GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors[keyof GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetErrors];

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses = {
    /**
     * Successful Response
     */
    200: FindingEvidenceListResponse;
};

export type GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponse = GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses[keyof GetAnalysisFindingEvidenceApiV1AnalysesAnalysisIdFindingsFindingIdEvidenceGetResponses];

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
        /**
         * Finding Id
         */
        finding_id: string;
    };
    query: {
        /**
         * Anchor Row
         */
        anchor_row: number;
        /**
         * Before
         */
        before?: number;
        /**
         * After
         */
        after?: number;
    };
    url: '/api/v1/analyses/{analysis_id}/findings/{finding_id}/row-context';
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetError = GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors[keyof GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetErrors];

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses = {
    /**
     * Successful Response
     */
    200: RowContextResponse;
};

export type GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponse = GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses[keyof GetAnalysisFindingRowContextApiV1AnalysesAnalysisIdFindingsFindingIdRowContextGetResponses];

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/profile';
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetError = GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors[keyof GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetErrors];

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisProfileResponse;
};

export type GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponse = GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses[keyof GetAnalysisProfileApiV1AnalysesAnalysisIdProfileGetResponses];

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}/status';
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetError = GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors[keyof GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetErrors];

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisStatusResponse;
};

export type GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponse = GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses[keyof GetAnalysisStatusApiV1AnalysesAnalysisIdStatusGetResponses];

export type PostDemoSalesApiV1DemoSalesPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo/sales';
};

export type PostDemoSalesApiV1DemoSalesPostResponses = {
    /**
     * Successful Response
     */
    202: DemoAnalysisResponse;
};

export type PostDemoSalesApiV1DemoSalesPostResponse = PostDemoSalesApiV1DemoSalesPostResponses[keyof PostDemoSalesApiV1DemoSalesPostResponses];

export type GetLivenessApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type GetLivenessApiV1HealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type GetLivenessApiV1HealthLiveGetResponse = GetLivenessApiV1HealthLiveGetResponses[keyof GetLivenessApiV1HealthLiveGetResponses];

export type GetReadinessApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type GetReadinessApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type GetReadinessApiV1HealthReadyGetResponse = GetReadinessApiV1HealthReadyGetResponses[keyof GetReadinessApiV1HealthReadyGetResponses];

export type GetVersionApiV1VersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type GetVersionApiV1VersionGetResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type GetVersionApiV1VersionGetResponse = GetVersionApiV1VersionGetResponses[keyof GetVersionApiV1VersionGetResponses];
